// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;
import game.Resource;
import java.util.EnumMap;

/************************************************************/
/**
 * 
 */
public class City extends SettlementStructure{

	/**
	 * 
	 * @param location 
	 * @param VP 
	 */

	private static final EnumMap<Resource, Integer> COST;
    
	static {
		COST = new EnumMap<>(Resource.class);
		COST.put(Resource.WHEAT, 2);
		COST.put(Resource.ORE, 3);
	}
	public City(Player owner) {
		super(owner);
		victoryPoints = 2;
	}

	@Override
	public void giveResourceToPlayer(Resource resource) {
		
	}

	@Override
	public EnumMap<Resource, Integer> getCost() {
		return new EnumMap<>(COST);
	}
}
