// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;

/************************************************************/
/**
 * 
 */
public class Road extends Structure{
	/**
	 * 
	 */
	public Road(Player owner) {
		super(owner);
	}
}
