// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;
import game.Resource;
import java.util.EnumMap;

/************************************************************/
/**
 * 
 */
public class Road extends Structure{
	/**
	 * 
	 */


	public Road(Player owner) {
		super(owner);
		COST.put(Resource.BRICK, 1);
		COST.put(Resource.WOOD, 1);
	}

    @Override
    public EnumMap<Resource, Integer> getCost() {
        return new EnumMap<>(COST);
    }
}
