// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Settlement {
	/**
	 * 
	 * @param location 
	 * @param VP 
	 */
	public void Settlement(Node location, int VP) {
	}
}
