// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;
import game.Resource;
import java.util.EnumMap;

/************************************************************/
/**
 * 
 */
public class Settlement extends SettlementStructure{
	/**
	 * 
	 * @param location 
	 * @param VP 
	 */
	public Settlement(Player owner) {
		super(owner);
		victoryPoints = 2;
		COST.put(Resource.BRICK, 1);
		COST.put(Resource.WOOD, 1);
		COST.put(Resource.WHEAT, 1);
		COST.put(Resource.SHEEP, 1);
	}



	@Override
	public void giveResourceToPlayer(Resource resource) {
        getOwner().addResource(resource, 1);
	}

  @Override
  public EnumMap<Resource, Integer> getCost() {
		return new EnumMap<>(COST); // Returns a copy of the original, not the actual thing
  }
}
