// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;

/************************************************************/
/**
 * 
 */
public class Settlement extends SettlementStructure{
	/**
	 * 
	 * @param location 
	 * @param VP 
	 */
	public Settlement(Player owner) {
		super(owner);
		victoryPoints = 2;
	}
}
