// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public abstract class SettlementStructure {
	/**
	 * 
	 */
	private int victoryPoints;

	/**
	 * 
	 * @return 
	 */
	public int getVP() {
	}
}
