// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;

/************************************************************/
/**
 * 
 */
public abstract class SettlementStructure extends Structure {
	/**
	 * 
	 */
	protected int victoryPoints;

	public SettlementStructure(Player owner) {
		super(owner);
	}

	/**
	 * 
	 * @return 
	 */
	public int getVP() {
		return victoryPoints;
	}
}
