// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @param owner 
	 */
	public void Structure(Player owner) {
	}
}
