// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;
import game.Resource;
import java.util.EnumMap;
/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	protected final EnumMap<Resource, Integer> COST;
	/**
	 * 
	 * @param owner 
	 */
	public Structure(Player owner) {
		this.owner = owner;
		COST = new EnumMap<>(Resource.class);
	}

	public abstract EnumMap<Resource, Integer> getCost();
	
	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}

}
