// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package structures;

import game.Player;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	
	/**
	 * 
	 * @param owner 
	 */
	public Structure(Player owner) {
	}
	
	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}

}
