// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.structures;

import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;

/************************************************************/
/**
 * 
 */
public class Road extends Structure {
	/**
	 * 
	 */
	public Road(Player owner) {
		super(owner);
		COST.put(Resource.BRICK, 1);
		COST.put(Resource.WOOD, 1);
	}
}
