// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.structures;

import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;

/************************************************************/
/**
 * 
 */
public class Settlement extends SettlementStructure{
	/**
	 * 
	 * @param location 
	 * @param VP 
	 */
	public Settlement(Player owner) {
		super(owner);
		victoryPoints = 1;
		COST.put(Resource.BRICK, 1);
		COST.put(Resource.WOOD, 1);
		COST.put(Resource.WHEAT, 1);
		COST.put(Resource.SHEEP, 1);
	}



	@Override
	public void giveResourceToPlayer(Resource resource) {
		getOwner().addResource(resource, 1);
	}
}
