// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.structures;

import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;

/************************************************************/
/**
 * 
 */
public abstract class SettlementStructure extends Structure {
	/**
	 * 
	 */
	protected int victoryPoints;

	public SettlementStructure(Player owner) {
		super(owner);
	}

	/**
	 * 
	 * @return 
	 */
	public int getVP() {
		return victoryPoints;
	}

	public abstract void giveResourceToPlayer(Resource resource);
}
