// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.structures;

import java.util.EnumMap;

import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	protected final EnumMap<Resource, Integer> COST = new EnumMap<>(Resource.class);
	/**
	 * 
	 * @param owner 
	 */
	public Structure(Player owner) {
		this.owner = owner;
	}
	
	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}

	public EnumMap<Resource, Integer> getCost() {
		return new EnumMap<Resource, Integer>(COST);
	}
}
