// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.structures;

import game.Player;
import game.Resource;

/************************************************************/
/**
 * 
 */
public class City extends SettlementStructure{
	/**
	 * 
	 * @param location 
	 * @param VP 
	 */
	public City(Player owner) {
		super(owner);
		victoryPoints = 2;
		COST.put(Resource.WHEAT, 2);
		COST.put(Resource.ORE, 3);
	}

	@Override
	public void giveResourceToPlayer(Resource resource) {
		getOwner().addResource(resource, 1);
	}
}
