// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.structures;

import game.Player;
import game.Resource;

/************************************************************/
/**
 * 
 */
public class Road extends Structure {
	/**
	 * 
	 */
	public Road(Player owner) {
		super(owner);
		COST.put(Resource.BRICK, 1);
		COST.put(Resource.WOOD, 1);
	}
}
