// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.structures;

import game.Player;
import game.Resource;
import java.util.EnumMap;
/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	protected final EnumMap<Resource, Integer> COST = new EnumMap<>(Resource.class);
	/**
	 * 
	 * @param owner 
	 */
	public Structure(Player owner) {
		this.owner = owner;
	}
	
	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}

	public EnumMap<Resource, Integer> getCost() {
		return new EnumMap<Resource, Integer>(COST);
	}
}
