// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

/************************************************************/
/**
 * 
 */
public interface Action {
	
	/**
	 * 
	 */
	public boolean execute();
	public void undo();
}
