// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import com.team22.catan.board.Board;
import com.team22.catan.board.NodePosition;
import com.team22.catan.game.Game;
import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;
import com.team22.catan.structures.Settlement;

/************************************************************/
/**
 * 
 */
public class BuildSettlement implements Action {
	private Player player;
	private Game game;
	private Board board;
	private NodePosition nodePosition;

	/**
	 * 
	 */
	public BuildSettlement(Player player, Game game, NodePosition nodePosition) {
		this.player = player;
    this.nodePosition = nodePosition;
		this.game = game;
    board = game.getBoard();
	}

	@Override
	public boolean execute() {
    Settlement settlement = new Settlement(player);
		if (game.getState() == GameState.SETUP) {
			if (!board.canPlaceSettlementAt(nodePosition, player, game.getState())) {
				System.out.println(player.getName() + " attempted to build a settlement but failed.");
				return false;
			} else {
				player.addVictoryPoints(1);
				board.placeSettlementAt(nodePosition, settlement, game.getState());
				System.out.println(player.getName() + " setup a settlement at " + nodePosition);
				return true;
			}
		} else {
			if (!player.canAfford(settlement.getCost())) {
				System.out.println(player.getName() +
						" attempted to build a new settlement but could not afford it.");
				return false;
			} else if (!board.canPlaceSettlementAt(nodePosition, player, game.getState())) {
				System.out.println(player.getName() + " attempted to build a new settlement but failed.");
				return false;
			} else {
				player.build(settlement);
				player.addVictoryPoints(1);
				board.placeSettlementAt(nodePosition, settlement, game.getState());
				System.out.println(player.getName() + " placed a settlement at " + nodePosition);
				return true;
			}
		}
	}

	@Override
	public void unExecute() {

	}
}
