// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import java.util.Map.Entry;

import com.team22.catan.board.Board;
import com.team22.catan.board.EdgePosition;
import com.team22.catan.game.Game;
import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;
import com.team22.catan.structures.Road;

/************************************************************/
/**
 * 
 */
public class BuildRoad implements Action {
  private Player player;
  private Game game;
  private Board board;
  private EdgePosition edgePosition;

  /**
   * 
   */
  public BuildRoad(Player player, Game game, EdgePosition edgePosition) {
    this.player = player;
    this.game = game;
    this.edgePosition = edgePosition;
    board = game.getBoard();
  }

  /**
   * 
   */
  @Override
  public boolean execute() {
    Road road = new Road(player);
    if (game.getState() == GameState.SETUP) {
      if (!board.canPlaceRoadAt(edgePosition, player, game.getState())) {
        System.out.println(player.getName() + " cannot place setup road at " + edgePosition);
        return false;
      } else {
        board.placeRoadAt(edgePosition, road, game.getState());
        player.setSetupRoad(true);
        System.out.println(player.getName() + " setup a road at " + edgePosition);
        return true;
      }
    } else {
      if (!player.canAfford(road.getCost())) {
        System.out.println(player.getName() +
            " attempted to build a new road but could not afford it.");
        return false;
      } else if (!board.canPlaceRoadAt(edgePosition, player, game.getState())) {
        System.out.println(player.getName() + " attempted to build a new road but failed.");
        return false;
      } else {
        player.build(road);
        board.placeRoadAt(edgePosition, road, game.getState());
        System.out.println(player.getName() + " placed a road at " + edgePosition);
        return true;
      }
    }
  }

  @Override
  public void undo() {
    System.out.println("Undoing build road action");
    Road removedRoad = board.removeRoadAt(edgePosition);
    if (game.getState() == GameState.SETUP) {
      player.setSetupRoad(false);
      // Since roads have to be placed after settlements, make sure that this is kept true
      player.setSetupSettlement(true);
    } else {
      for (Entry<Resource, Integer> resource : removedRoad.getCost().entrySet()) {
        player.addResource(resource.getKey(), resource.getValue());
      }
    }
  }
}
