// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import java.util.Map.Entry;

import com.team22.catan.board.Board;
import com.team22.catan.board.NodePosition;
import com.team22.catan.game.Game;
import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;
import com.team22.catan.structures.City;

/************************************************************/
/**
 * 
 */
public class BuildCity implements Action {
	private Player player;
	private Game game;
	private Board board;
	private NodePosition nodePosition;
	/**
	 * 
	 */
	public BuildCity(Player player, Game game, NodePosition nodePosition) {
		this.player = player;
		this.game = game;
		this.board = game.getBoard();
		this.nodePosition = nodePosition;
	}



	@Override
	public boolean execute() {
		City city = new City(player);
    if (!player.canAfford(city.getCost())) {
			System.out.println(player.getName() +
					" attempted to build a new city but could not afford it.");
			return false;
		} else if (!board.canPlaceCityAt(nodePosition, player, game.getState())) {
			System.out.println(player.getName() + " attempted to build a new city but failed.");
			return false;
		} else {
			player.build(city);
			player.addVictoryPoints(1);
			board.placeCityAt(nodePosition, city, game.getState());
			System.out.println(player.getName() + " placed a city at " + nodePosition);
			return true;
		}
	}

	@Override
	public void undo() {
		System.out.println("Undoing build city action");
		City removedCity = board.removeCityAt(nodePosition);
		for (Entry<Resource, Integer> resource : removedCity.getCost().entrySet()) {
			player.addResource(resource.getKey(), resource.getValue());
		}
		
		player.addVictoryPoints(-1);
	}
}
