// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import com.team22.catan.board.Board;
import com.team22.catan.board.EdgePosition;
import com.team22.catan.game.Game;
import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;
import com.team22.catan.structures.Road;

/************************************************************/
/**
 * 
 */
public class BuildRoad implements Action {
	private Player player;
	private Game game;
	private Board board;
	private EdgePosition edgePosition;

	/**
	 * 
	 */
	public BuildRoad(Player player, Game game, EdgePosition edgePosition) {
		this.player = player;
		this.game = game;
		this.edgePosition = edgePosition;
		board = game.getBoard();
	}

	/**
	 * 
	 */
	@Override
	public void execute() {
		Road road = new Road(player);
		if (game.getState() == GameState.SETUP) {
			if (!board.canPlaceRoadAt(edgePosition, player)) {
				System.out.println(player.getName() + " cannot place setup road at " + edgePosition);
			} else {
				board.placeRoadAt(edgePosition, road);
				System.out.println(player.getName() + " setup a road at " + edgePosition);
			}
		} else {
			if (!player.canAfford(road.getCost())) {
				System.out.println(player.getName() +
						" attempted to build a new road but could not afford it.");
			} else if (!board.canPlaceRoadAt(edgePosition, player)) {
				System.out.println(player.getName() + " attempted to build a new road but failed.");
			} else {
				player.build(road);
				board.placeRoadAt(edgePosition, road);
				System.out.println(player.getName() + " placed a road at " + edgePosition);
			}
		}
	}
}
