// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import com.team22.catan.game.Game;
import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;

/************************************************************/
/**
 * 
 */
public class EndTurn implements Action {
  private Player player;
  private Game game;

  /**
   * 
   */
  public EndTurn(Player player, Game game) {
    this.player = player;
    this.game = game;
  }

  @Override
  public boolean execute() {

    if (game.getState() == GameState.SETUP || player.getDiceRolled()) {
      System.out.println(player.getName() + " has ended their turn. ");
      player.setDiceRolled(false);
      game.onEndTurn();
      return true;
    } else {
      System.out.println(player.getName() + " still needs to roll before ending their turn!");
      return false;
    }
  }

  public void undo() {
    int currentPlayerIndex = game.getCurrentPlayerIndex();
    currentPlayerIndex--;
    if (currentPlayerIndex < 0) {
      currentPlayerIndex = game.getPlayers().size() - 1;
    }

    game.setCurrentPlayerIndex(currentPlayerIndex);
  }
}
