// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.actions;

import com.team22.catan.game.Game;
import com.team22.catan.game.Player;

/************************************************************/
/**
 * 
 */
public class EndTurn implements Action {
	private Player player;
	private Game game;
	/**
	 * 
	 */
	public EndTurn(Player player, Game game) {
		this.player = player;
		this.game = game;
	}

	/**
	 * 
	 */
	@Override
	public void execute() {
		System.out.println(player.getName() + " has ended their turn. ");
		game.onEndTurn();
	}
}
