// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.actions;

/************************************************************/
/**
 * 
 */
public interface Action {
	
	/**
	 * 
	 */
	public void execute();
}
