// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.actions;


import board.Node;
import board.Board;
import board.NodePosition;
import game.Game;
import game.GameState;
import game.Player;
import structures.Settlement;

/************************************************************/
/**
 * 
 */
public class BuildSettlement implements Action {
	private Player player;
	private Game game;
	private Board board;
	private NodePosition nodePosition;

	/**
	 * 
	 */
	public BuildSettlement(Player player, Game game, NodePosition nodePosition) {
		this.player = player;
    this.nodePosition = nodePosition;
		this.game = game;
    board = game.getBoard();
	}

	/**
	 * 
	 */
	@Override
	public void execute() {
    Settlement settlement = new Settlement(player);
		Node node = board.getNodes().get(nodePosition);
		if (game.getState() == GameState.SETUP) {
			if (node.getStructure() != null || !node.distanceRule()) {
				System.out.println(player.getName() + " attempted to build a settlement but failed.");
			} else {
				player.addVictoryPoints(1);
				node.placeSettlement(settlement, game);
				System.out.println(player.getName() + " setup a settlement at " + nodePosition);
			}
		} else {
			if (!player.canAfford(settlement.getCost())) {
				System.out.println(player.getName() +
						" attempted to build a new settlement but could not afford it.");
			} else if (!node.canPlaceSettlement(player)) {
				System.out.println(player.getName() + " attempted to build a new settlement but failed.");
			} else {
				player.build(settlement);
				player.addVictoryPoints(1);
				node.placeSettlement(settlement, game);
				System.out.println(player.getName() + " placed a settlement at " + nodePosition);
			}
		}
	}
}
