// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class ComputerPlayer {
	/**
	 * 
	 * @param name 
	 */
	public void ComputerPlayer(String name) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @return 
	 */
	public void getResourceList() {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void addResource(undef resource) {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void build(Structure structure) {
	}

	/**
	 * 
	 */
	public void makeMove() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
