// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import actions.Action;
import actions.BuildCity;
import actions.BuildRoad;
import actions.BuildSettlement;
import actions.EndTurn;
import board.Edge;
import board.Node;
import structures.City;
import structures.Road;
import structures.Settlement;

public class ComputerPlayer extends Player {

  private Random rng;

  public ComputerPlayer(String name, Random rng) {
    super(name);
    this.rng = rng;
  }

  @Override
  public void onTurn(Game game) {
    List<Action> availableActions = getAvailableActions(game);

    if (game.getState() == GameState.SETUP) {
      for (Action action : availableActions) {
        action.execute();
      }
    } else {
      availableActions.get(rng.nextInt(availableActions.size())).execute();
    }
  }

  private List<Action> getAvailableActions(Game game) {
    List<Action> actionsToReturn = new ArrayList<>();

    if (game.getState() == GameState.SETUP) {
      List<Action> possibleSettlementPlacements = new ArrayList<>();
      List<Action> possibleRoadPlacements = new ArrayList<>();
      for (Node node : game.getBoard().getNodes().values()) {
        if (node.getStructure() == null && node.distanceRule()) {
          possibleSettlementPlacements.add(
              new BuildSettlement(this, game.getBoard(), node.getPosition()));

          for (Edge edge : node.getEdges()) {
            if (edge.getRoad() == null) {
              possibleRoadPlacements.add(new BuildRoad(this, game.getBoard(), edge.getPosition()));
            }
          }
        }
      }

      actionsToReturn.add(possibleSettlementPlacements.get(rng.nextInt(possibleSettlementPlacements.size())));
      actionsToReturn.add(possibleRoadPlacements.get(rng.nextInt(possibleRoadPlacements.size())));
      actionsToReturn.add(new EndTurn(this, game));

    } else {
      actionsToReturn.add(new EndTurn(this, game));

      for (Node node : game.getBoard().getNodes().values()) {
        if (node.canPlaceSettlement(this) && canAfford(new Settlement(this).getCost())) {
          actionsToReturn.add(new BuildSettlement(this, game.getBoard(), node.getPosition()));
        }

        if (node.canPlaceCity(this) && canAfford(new City(this).getCost())) {
          actionsToReturn.add(new BuildCity(this, game.getBoard(), node.getPosition()));
        }
      }

      for (Edge edge : game.getBoard().getEdges().values()) {
        if (edge.canPlaceRoad(this) && canAfford(new Road(this).getCost())) {
          actionsToReturn.add(new BuildRoad(this, game.getBoard(), edge.getPosition()));
        }
      }
    }

    return actionsToReturn;
  }
}
