// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private int sides;

	/**
	 * 
	 * @param sides 
	 */
	public void Dice(int sides) {
	}

	/**
	 * 
	 * @param numDice 
	 * @return 
	 */
	public int[] rollDice(int numDice) {
	}
}
