// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package game;

public class Dice {
	private final static int SIDES = 6;

	/**
	 * 
	 * @param n [Number of dice to roll]
	 * @return Returns n rolled dice values all added together
	 */
	public int rollDice(int n) {
        int total = 0;
        for(int i = 0; i < n; i++) { total += (int)(Math.random() * SIDES) + 1; }
        return total;
	}
}
