// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package game;
/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private int sides;

	/**
	 * 
	 * @param sides 
	 */
	public Dice(int sides) {
	}

	/**
	 * 
	 * @param numDice 
	 * @return 
	 */
	public int[] rollDice(int numDice) {
		return new int[] {0, 0};
	}
}
