// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int turns;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private static Random rng;

	/**
	 * 
	 * @param turns 
	 * @param board 
	 * @param players 
	 */
	public void Game(int turns, Board board, Player[] players) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void addPlayer(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player[] getPlayers() {
	}

	/**
	 * 
	 * @return 
	 */
	public Board getBoard() {
	}

	/**
	 * 
	 * @param name 
	 * @return 
	 */
	public String searchPlayer(String name) {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
