// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

// Location of its directory
package game;

import java.util.ArrayList;
// All the java directories we import
import java.util.List;
import java.util.Random;

// All the directories we import
import board.Board;

public class Game {
  private int turns;
  private int currentTurn;
  private List<Player> players;
  private int currentPlayerIndex;
  private Random rng;
  private Dice dice;
  private Board board;
  private GameState gameState;

  /**
   * 
   * @param turns   [Unchanging number of turns of the game]
   * @param board   [Unchanging board, ie a single board doesnt get replaced by
   *                another obj]
   * @param players [Unchanging number of players]
   */
  public Game(int turns, Board board, List<Player> players) {
    this.turns = turns;
    currentTurn = 1; // Starting at turn 1
    this.players = players;
    this.board = board;
    dice = new Dice(rng);
    currentPlayerIndex = 0; // First player to go is at index 0
    gameState = GameState.SETUP;
  }

  public GameState getState() {
    return gameState;
  }

  /**
   * @return Returns the player list
   */
  public List<Player> getPlayers() {
    return new ArrayList<>(players);
  }

  /**
   * @return Returns the board obj
   */
  public Board getBoard() {
    return board;
  }

  public int rollDice() {
    return dice.rollDice(2);
  }

  public void endGame() {
    System.out.println("\nGame over!");
    displayResults();
  }

  public void play() {
    System.out.println("Starting Catan game with " + players.size() + " players");
    System.out.println("Playing for " + turns + " turns");
    System.out.println("\n" + players.get(currentPlayerIndex).getName() + "'s turn");

    while (currentTurn <= turns && !checkWinCondition()) {
      processPlayerTurn();
    }

    endGame();
  }

  private void processPlayerTurn() {
    players.get(currentPlayerIndex).onTurn(this);
  }

  public void onEndTurn() {
    if (currentPlayerIndex == players.size() - 1) {
      currentTurn++;
    }

    currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
    System.out.println("\n" + players.get(currentPlayerIndex).getName() + "'s turn");
    board.notifyTilesOfRoll(rollDice());
  }

  /**
   * Displays the final game results.
   */
  private void displayResults() {
    System.out.println("\nFinal Standings:");
    for (Player player : players) {
      int victoryPoints = player.getVictoryPoints();
      System.out.println(player.getName() + ": " + victoryPoints + " VP");
    }
  }

  private boolean checkWinCondition() {
    for (Player player : players) {
      if (player.getVictoryPoints() >= CatanSettings.WINNING_VP_COUNT) {
        return true;
      }
    }

    return false;
  }

  @Override
  public String toString() {
    return board.toString();
  }
}
