// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package game;

import java.util.HashMap;
import java.util.Map;
import structures.Structure;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	private final String playerName;
	/**
	 * 
	 */
	private HashMap<Resource, Integer> inventory;

	/**
	 * 
	 * @param name 
	 */
	public Player(String name) {
		playerName = name;
		inventory = new HashMap<>();
		initiateMap();
	}

	private void initiateMap() {

		for (Resource resource : Resource.values()) {
			inventory.put(resource, 0);
		}
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
		return playerName;
	}

	public Map<Resource, Integer> getInventory() {
		return this.inventory;
	}

	public Integer getResource (Resource resource) {
		return inventory.get(resource);
	}

	public void addResource(Resource material, int number) {
		int value = inventory.get(material) + number;
		inventory.put(material, value);
	}



	/**
	 * 
	 */
	public void removeResource() {
	}


	/**
	 * 
	 * @param structure 
	*/
	public void build(Structure structure) {
	}

	@Override
	public String toString() {
		StringBuilder res = new StringBuilder();

		res.append(this.playerName);
		res.append(" Resources: \n");
		for (Map.Entry<Resource, Integer> entry : this.inventory.entrySet()) {
			res.append("\t");
			res.append(entry.getKey());
			res.append(" : ");
			res.append(entry.getValue());
			res.append("\n");
		}

		return res.toString();
	}

	/**
	 * 
	 */
	public abstract void makeMove();
}
