// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package game;

import java.util.EnumMap;

import structures.Structure;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	private String playerName;
	/**
	 * 
	 */
	private EnumMap<Resource, Integer>[] inventory;

	/**
	 * 
	 * @param name 
	 */
	public Player(String name) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
		return playerName;
	}

	/**
	 * 
	 * @return 
	 */
	public EnumMap<Resource, Integer> getInventory() {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void addResource(Resource resource) {
	}

	
	
	/**
	 * 
	 */
	public void removeResource() {
	}

	
	/**
	 * 
	 * @param structure 
	*/
	public void build(Structure structure) {
	}
	
	/**
	 * 
	 * @return 
	*/
	public String toString() {
	}
	
	/**
	 * 
	 */
	public abstract void makeMove();
}
