// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.team22.catan.actions.Action;
import com.team22.catan.actions.BuildCity;
import com.team22.catan.actions.BuildRoad;
import com.team22.catan.actions.BuildSettlement;
import com.team22.catan.actions.EndTurn;
import com.team22.catan.actions.GenerateResources;
import com.team22.catan.board.EdgePosition;
import com.team22.catan.board.NodePosition;
import com.team22.catan.structures.City;
import com.team22.catan.structures.Road;
import com.team22.catan.structures.Settlement;


public class ComputerPlayer extends Player {

  private Random rng;
  private Parser parser;
  private ActionEvaluator evaluator;

  public ComputerPlayer(String name, PlayerColor color, Random rng, Parser parser) {
    super(name, color);
    this.rng = rng;
    this.parser = parser;
    this.evaluator = new StandardActionEvaluator();
  }

  public void setEvaluator(ActionEvaluator evaluator) {
      this.evaluator = evaluator;
  }

  @Override
  public void onTurn(Game game) {
      List<Action> availableActions = getAvailableActions(game);

      if (game.getState() == GameState.SETUP) {
          setupTurn(game);
      } else {
          // Prevent crashing if no actions are somehow available
          if (availableActions.isEmpty()) {
              game.executeAction(new EndTurn(this, game));
              return;
          }

          double highestScore = -1.0;
          List<Action> tiedBestActions = new ArrayList<>();

          // Evaluate every possible action using the Strategy Pattern
          for (Action action : availableActions) {
              double score = evaluator.evaluate(action, this);

              System.out.println(getName() + " considered " + action.getClass().getSimpleName() + " | Score: " + score);

              if (score > highestScore) {
                  highestScore = score;
                  tiedBestActions.clear();
                  tiedBestActions.add(action);
              } else if (score == highestScore) {
                  // Keep track of ties to choose randomly later
                  tiedBestActions.add(action);
              }
          }

          // Choose a random action from the tie-pool (Requirement R3.2)
          Action bestAction = tiedBestActions.get(rng.nextInt(tiedBestActions.size()));
          game.executeAction(bestAction);
      }
  }

  private void setupTurn(Game game) {
    if (!getSetupSettlement()) {
      List<Action> possibleSettlementPlacements = new ArrayList<>();
      for (NodePosition nodePosition : game.getBoard().getNodePositions()) {
        if (game.getBoard().canPlaceSettlementAt(nodePosition, this, game.getState())) {
          possibleSettlementPlacements.add(new BuildSettlement(this, game, nodePosition));
        }
      }

      game.executeAction(possibleSettlementPlacements.get(rng.nextInt(possibleSettlementPlacements.size())));
    }

    if (!getSetupRoad()) {
      List<Action> possibleRoadPlacements = new ArrayList<>();
      for (EdgePosition edgePosition : game.getBoard().getEdgePositions()) {
        if (game.getBoard().canPlaceRoadAt(edgePosition, this, game.getState())) {
          possibleRoadPlacements.add(new BuildRoad(this, game, edgePosition));
        }
      }

      game.executeAction(possibleRoadPlacements.get(rng.nextInt(possibleRoadPlacements.size())));
    }

    game.executeAction(new EndTurn(this, game));
  }

  private List<Action> getAvailableActions(Game game) {
    List<Action> actionsToReturn = new ArrayList<>();
    if (!getDiceRolled()) {
      actionsToReturn.add(new GenerateResources(this, game));
    }
    
    for (NodePosition nodePosition : game.getBoard().getNodePositions()) {
      if (game.getBoard().canPlaceSettlementAt(nodePosition, this, game.getState()) &&
          canAfford(new Settlement(this).getCost())) {

        actionsToReturn.add(new BuildSettlement(this, game, nodePosition));
      }

      if (game.getBoard().canPlaceCityAt(nodePosition, this, game.getState()) &&
          canAfford(new City(this).getCost())) {

        actionsToReturn.add(new BuildCity(this, game, nodePosition));
      }
    }

    for (EdgePosition edgePosition : game.getBoard().getEdgePositions()) {
      if (game.getBoard().canPlaceRoadAt(edgePosition, this, game.getState()) &&
          canAfford(new Road(this).getCost())) {

        actionsToReturn.add(new BuildRoad(this, game, edgePosition));
      }
    }

    // Only allow the player to end their turn if they either have less
    // than 7 cards or they can't build anything
    if ((getResourceCountTotal() < 7 || actionsToReturn.isEmpty()) && getDiceRolled()) {
      actionsToReturn.add(new EndTurn(this, game));
    }

    return actionsToReturn;
  }
}
