// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.team22.catan.actions.Action;
import com.team22.catan.actions.BuildCity;
import com.team22.catan.actions.BuildRoad;
import com.team22.catan.actions.BuildSettlement;
import com.team22.catan.actions.EndTurn;
import com.team22.catan.actions.GenerateResources;
import com.team22.catan.board.EdgePosition;
import com.team22.catan.board.NodePosition;
import com.team22.catan.structures.City;
import com.team22.catan.structures.Road;
import com.team22.catan.structures.Settlement;

public class ComputerPlayer extends Player {

  private Random rng;
  private Parser parser;

  public ComputerPlayer(String name, PlayerColor color, Random rng, Parser parser) {
    super(name, color);
    this.rng = rng;
    this.parser = parser;
  }

  @Override
  public void onTurn(Game game) {

    parser.waitForGoCommand();

    List<Action> availableActions = getAvailableActions(game);

    if (game.getState() == GameState.SETUP) {
      setupTurn(game);
    } else {
      availableActions.get(rng.nextInt(availableActions.size())).execute();
    }
  }

  private void setupTurn(Game game) {
    List<Action> possibleSettlementPlacements = new ArrayList<>();
    for (NodePosition nodePosition : game.getBoard().getNodePositions()) {
      if (game.getBoard().canPlaceSettlementAt(nodePosition, this, game.getState())) {
        possibleSettlementPlacements.add(new BuildSettlement(this, game, nodePosition));
      }
    }

    possibleSettlementPlacements.get(rng.nextInt(possibleSettlementPlacements.size())).execute();

    List<Action> possibleRoadPlacements = new ArrayList<>();
    for (EdgePosition edgePosition : game.getBoard().getEdgePositions()) {
      if (game.getBoard().canPlaceRoadAt(edgePosition, this, game.getState())) {
        possibleRoadPlacements.add(new BuildRoad(this, game, edgePosition));
      }
    }

    possibleRoadPlacements.get(rng.nextInt(possibleRoadPlacements.size())).execute();

    new EndTurn(this, game).execute();
  }

  private List<Action> getAvailableActions(Game game) {
    List<Action> actionsToReturn = new ArrayList<>();
    if (!diceRolled) {
      actionsToReturn.add(new GenerateResources(this, game));
    }
    
    for (NodePosition nodePosition : game.getBoard().getNodePositions()) {
      if (game.getBoard().canPlaceSettlementAt(nodePosition, this, game.getState()) &&
          canAfford(new Settlement(this).getCost())) {

        actionsToReturn.add(new BuildSettlement(this, game, nodePosition));
      }

      if (game.getBoard().canPlaceCityAt(nodePosition, this, game.getState()) &&
          canAfford(new City(this).getCost())) {

        actionsToReturn.add(new BuildCity(this, game, nodePosition));
      }
    }

    for (EdgePosition edgePosition : game.getBoard().getEdgePositions()) {
      if (game.getBoard().canPlaceRoadAt(edgePosition, this, game.getState()) &&
          canAfford(new Road(this).getCost())) {

        actionsToReturn.add(new BuildRoad(this, game, edgePosition));
      }
    }

    // Only allow the player to end their turn if they either have less
    // than 7 cards or they can't build anything
    if ((getResourceCountTotal() < 7 || actionsToReturn.isEmpty()) && diceRolled) {
      actionsToReturn.add(new EndTurn(this, game));
    }

    return actionsToReturn;
  }
}
