// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.game;

import java.util.Random;

public class Dice {
	private int SIDES = 6;
	private Random rng;

	public Dice(Random rng) {
		this.rng = rng;
	}

	/**
	 * 
	 * @param n [Number of dice to roll]
	 * @return Returns n rolled dice values all added together
	 */
	public int rollDice(int n) {
        int total = 0;
        for(int i = 0; i < n; i++) {
					total += rng.nextInt(SIDES) + 1; 
				}

        return total;
	}
}
