// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

// Location of its directory
package com.team22.catan.game;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.Stack;

import com.team22.catan.actions.Action;
import com.team22.catan.board.Board;

public class Game {
  private Random rng;
  private int turns;
  private int currentTurn;
  private List<Player> players;
  private int currentPlayerIndex;
  private Dice dice;
  private Board board;
  private GameState gameState;

  private Stack<Action> actionHistory;
  private Stack<Action> undoHistory;

  /**
   * 
   * @param turns   [Unchanging number of turns of the game]
   * @param board   [Unchanging board, ie a single board doesnt get replaced by
   *                another obj]
   * @param players [Unchanging number of players]
   */
  public Game(int turns, Board board, List<Player> players, Dice dice, Random rng) {
    this.rng = rng;
    this.turns = turns;
    currentTurn = 1; // Starting at turn 1
    this.players = players;
    this.board = board;
    this.dice = dice;
    currentPlayerIndex = 0; // First player to go is at index 0
    gameState = GameState.SETUP;
    actionHistory = new Stack<>();
    undoHistory = new Stack<>();
  }

  public GameState getState() {
    return gameState;
  }

  /**
   * @return Returns the player list
   */
  public List<Player> getPlayers() {
    return new ArrayList<>(players);
  }

  public int getCurrentPlayerIndex() {
    return currentPlayerIndex;
  }

  public void setCurrentPlayerIndex(int index) {
    if (index < 0 || index >= players.size()) {
      throw new IllegalArgumentException("Player index must be between 0 and the player count");
    }

    currentPlayerIndex = index;
  }

  /**
   * @return Returns the board obj
   */
  public Board getBoard() {
    return board;
  }

  public int rollDice() {
    return dice.rollDice(CatanSettings.NUMBER_OF_DICE);
  }

  public Random getRng() {
    return rng;
  }

  private void endGame() {
    System.out.println("\nGame over!");
    displayResults();
  }

  public void play() {
    System.out.println("Starting Catan game with " + players.size() + " players");
    System.out.println("Playing for " + turns + " turns");

    setup();
    System.out.println("\n############### GAME START ###############");
    System.out.println("\n########## TURN " + currentTurn + " ###############");
    System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####");

    while (gameState != GameState.END) {
      processPlayerTurn();
      checkWinCondition();
    }

    endGame();
  }

  private void setup() {
    System.out.println("############### SETUP PHASE ###############");
    while (currentPlayerIndex < players.size()) {
      Player currentPlayer = players.get(currentPlayerIndex);
      System.out.println("\n##### " + currentPlayer.getName() + "'s turn #####\n");
      processPlayerTurn();
      currentPlayerIndex++;
    }

    for (Player player : players) {
      player.setSetupSettlement(false);
      player.setSetupRoad(false);
    }

    Collections.reverse(players);
    currentPlayerIndex = 0;
    while (currentPlayerIndex < players.size()) {
      System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####");
      processPlayerTurn();
      currentPlayerIndex++;
    }

    Collections.reverse(players);
    currentPlayerIndex = 0;

    System.out.println("\n##### Handing out initial items #####\n");
    for (int i = 2; i <= 12; i++) {
      board.notifyTilesOfRoll(i);
    }

    System.out.println("\n############### SETUP OVER ###############");
    gameState = GameState.PLAYING;
  }

  private void processPlayerTurn() {
    players.get(currentPlayerIndex).onTurn(this);
  }

  public boolean executeAction(Action action) {
    if (action.execute()) {
      actionHistory.push(action);
      undoHistory.clear();
      return true;
    }

    return false;
  }

  public void undo() {
    if (actionHistory.isEmpty()) {
      System.out.println("Nothing to undo");
      return;
    }
    
    Action action = actionHistory.pop();
    if (action != null) {
      action.undo();
      undoHistory.push(action);
    }
  }

  public void redo() {
    if (undoHistory.isEmpty()) {
      System.out.println("Nothing to redo");
      return;
    }

    Action action = undoHistory.pop();
    if (action != null && action.execute()) {
      actionHistory.push(action);
    }
  }

  public void onEndTurn() {
    checkWinCondition();

    if (currentPlayerIndex == players.size() - 1 && gameState == GameState.PLAYING) {
      System.out.println("\nVictory Point Standings:");
      displayVPStandings();

      if (currentTurn < turns) {
        currentTurn++;
        System.out.println("\n########## TURN " + currentTurn + " ###############");
      } else {
        System.out.println("Maximum turns reached. Game ending.");
        gameState = GameState.END;
      }
    }

    if (gameState == GameState.PLAYING) {
      currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
      Player nextPlayer = players.get(currentPlayerIndex);

      System.out.println("\n##### " + nextPlayer.getName() + "'s turn #####");

    } else if (gameState == GameState.END) {
      displayResults();
    }
  }

  /**
   * Displays the final game results.
   */
  private void displayResults() {
    System.out.println("\nFinal Standings:");
    displayVPStandings();
  }

  private void displayVPStandings() {
    for (Player player : players) {
      int victoryPoints = player.getVictoryPoints();
      System.out.println(player.getName() + ": " + victoryPoints + " VP");
    }
  }

  private void checkWinCondition() {
    for (Player player : players) {
      if (player.getVictoryPoints() >= CatanSettings.WINNING_VP_COUNT) {
        gameState = GameState.END;
      }
    }
  }

  @Override
  public String toString() {
    return board.toString();
  }
}
