// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

// Location of its directory
package com.team22.catan.game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Stack;
import java.util.Map.Entry;

import com.team22.catan.actions.Action;
import com.team22.catan.board.Board;

public class Game {
  private Random rng;
  private int turns;
  private int currentTurn;
  private List<Player> players;
  private int currentPlayerIndex;
  private Dice dice;
  private Board board;
  private GameState gameState;

  private Stack<Action> actionHistory;
  private Stack<Action> undoHistory;

  /**
   * 
   * @param turns   [Unchanging number of turns of the game]
   * @param board   [Unchanging board, ie a single board doesnt get replaced by
   *                another obj]
   * @param players [Unchanging number of players]
   */
  public Game(int turns, Board board, List<Player> players, Dice dice, Random rng) {
    this.rng = rng;
    this.turns = turns;
    currentTurn = 1; // Starting at turn 1
    this.players = players;
    this.board = board;
    this.dice = dice;
    currentPlayerIndex = 0; // First player to go is at index 0
    gameState = GameState.SETUP;
    actionHistory = new Stack<>();
    undoHistory = new Stack<>();
  }

  public GameState getState() {
    return gameState;
  }

  /**
   * @return Returns the player list
   */
  public List<Player> getPlayers() {
    return new ArrayList<>(players);
  }

  /**
   * @return Returns the board obj
   */
  public Board getBoard() {
    return board;
  }

  public int rollDice() {
    return dice.rollDice(CatanSettings.NUMBER_OF_DICE);
  }

  public Random getRng() {
    return rng;
  }

  private void endGame() {
    System.out.println("\nGame over!");
    displayResults();
  }

  public void play() {
    System.out.println("Starting Catan game with " + players.size() + " players");
    System.out.println("Playing for " + turns + " turns");

    System.out.println("\n########## TURN " + currentTurn + " ###############");
    System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####");

    while (gameState != GameState.END) {
      processPlayerTurn();
      checkWinCondition();
    }

    endGame();
  }

  private void processPlayerTurn() {
    players.get(currentPlayerIndex).onTurn(this);
  }

  public boolean executeAction(Action action) {
    if (action.execute()) {
      actionHistory.push(action);
      undoHistory.clear();
      return true;
    }

    return false;
  }

  public void undo() {
    if (actionHistory.isEmpty()) {
      System.out.println("Nothing to undo");
      return;
    }

    Action action = actionHistory.pop();
    if (action != null) {
      action.undo();
      undoHistory.push(action);
    }
  }

  public void redo() {
    if (undoHistory.isEmpty()) {
      System.out.println("Nothing to redo");
      return;
    }

    Action action = undoHistory.pop();
    if (action != null && action.execute()) {
      actionHistory.push(action);
    }
  }

  public void onEndTurn() {
    if (gameState == GameState.SETUP) {
      endSetupTurn();
    }

    if (currentPlayerIndex == players.size() - 1 && currentTurn < turns) {
      currentTurn++;
      System.out.println("\n########## TURN " + currentTurn + " ###############");
    } else if (currentTurn >= turns) {
      System.out.println("Maximum turns reached. Game ending.");
      gameState = GameState.END;
      displayResults();
      return;
    }

    currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
    Player nextPlayer = players.get(currentPlayerIndex);

    System.out.println("\n##### " + nextPlayer.getName() + "'s turn #####");
  }

  public void onUndoEndTurn(GameState previousState) {
    if (previousState == GameState.SETUP) {
      undoEndSetupTurn();
    }

    if (currentPlayerIndex == 0 && currentTurn > 1) {
      currentTurn--;
    } else if (currentPlayerIndex == 0 && currentTurn <= 1) {
      throw new IllegalStateException("Cannot go back a turn on turn 1");
    }

    currentPlayerIndex--;
    if (currentPlayerIndex < 0) {
      currentPlayerIndex = players.size() - 1;
    }
  }

  private void endSetupTurn() {
    if (currentPlayerIndex == players.size() - 1) {
      for (Player player : players) {
        player.setSetupRoad(false);
        player.setSetupSettlement(false);
      }

      if (currentTurn == CatanSettings.SETUP_TURNS) {
        System.out.println("\n############### SETUP OVER ###############");
        System.out.println("\nHanding out initial resources...\n");
        // Dice are assumed to be 6 sided, hence multiply by 6 to get max roll
        for (int i = CatanSettings.NUMBER_OF_DICE; i <= CatanSettings.NUMBER_OF_DICE * 6; i++) {
          board.notifyTilesOfRoll(i); // Hand out initial resources
        }

        gameState = GameState.PLAYING;
      }

      Collections.reverse(players);
    }
  }

  private void undoEndSetupTurn() {
    if (currentPlayerIndex == 0) {
      for (Player player : players) {
        player.setSetupRoad(true);
        player.setSetupSettlement(true);
      }

      if (currentTurn == CatanSettings.SETUP_TURNS + 1) {
        gameState = GameState.SETUP;
        emptyPlayerInventories();
      }
    }

    Collections.reverse(players);
  }

  private void emptyPlayerInventories() {
    for (Player player : players) {
      Map<Resource, Integer> inventory = player.getInventory();
      for (Entry<Resource, Integer> resource : inventory.entrySet()) {
        player.addResource(resource.getKey(), -resource.getValue());
      }
    }
  }

  /**
   * Displays the final game results.
   */
  private void displayResults() {
    System.out.println("\nFinal Standings:");
    displayVPStandings();
  }

  private void displayVPStandings() {
    for (Player player : players) {
      int victoryPoints = player.getVictoryPoints();
      System.out.println(player.getName() + ": " + victoryPoints + " VP");
    }
  }

  private void checkWinCondition() {
    for (Player player : players) {
      if (player.getVictoryPoints() >= CatanSettings.WINNING_VP_COUNT) {
        gameState = GameState.END;
      }
    }
  }

  @Override
  public String toString() {
    return board.toString();
  }
}
