// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

// Location of its directory
package com.team22.catan.game;

// All the java directories we import
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

// All the directories we import
import com.team22.catan.board.Board;

public class Game {
  private Random rng;
  private int turns;
  private int currentTurn;
  private List<Player> players;
  private int currentPlayerIndex;
  private Dice dice;
  private Board board;
  private GameState gameState;

  /**
   * 
   * @param turns   [Unchanging number of turns of the game]
   * @param board   [Unchanging board, ie a single board doesnt get replaced by
   *                another obj]
   * @param players [Unchanging number of players]
   */
  public Game(int turns, Board board, List<Player> players, Dice dice, Random rng) {
    this.rng = rng;
    this.turns = turns;
    currentTurn = 1; // Starting at turn 1
    this.players = players;
    this.board = board;
    this.dice = dice;
    currentPlayerIndex = 0; // First player to go is at index 0
    gameState = GameState.SETUP;
  }

  public GameState getState() {
    return gameState;
  }

  /**
   * @return Returns the player list
   */
  public List<Player> getPlayers() {
    return new ArrayList<>(players);
  }

  /**
   * @return Returns the board obj
   */
  public Board getBoard() {
    return board;
  }

  public int rollDice() {
    return dice.rollDice(2);
  }

  private void endGame() {
    System.out.println("\nGame over!");
    displayResults();
  }

  public void play() {
    System.out.println("Starting Catan game with " + players.size() + " players");
    System.out.println("Playing for " + turns + " turns");

    setup();
    System.out.println("\n############### GAME START ###############");
    System.out.println("\n########## TURN " + currentTurn + " ###############");
    System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####");
    generateResources();

    while (gameState != GameState.END) {
      processPlayerTurn();
      checkWinCondition();
    }

    endGame();
  }

  private void setup() {
    System.out.println("############### SETUP PHASE ###############");
    for (int i = 0; i < players.size(); i++) {
      currentPlayerIndex = i;
      System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####\n");
      processPlayerTurn();
    }

    for (int i = players.size() - 1; i >= 0; i--) {
      currentPlayerIndex = i;
      System.out.println("\n##### " + players.get(currentPlayerIndex).getName() + "'s turn #####");
      processPlayerTurn();
    }

    System.out.println("\n##### Handing out initial items #####\n");
    for (int i = 2; i <= 12; i++) {
      board.notifyTilesOfRoll(i);
    }

    System.out.println("\n############### SETUP OVER ###############");
    gameState = GameState.PLAYING;
  }

  private void processPlayerTurn() {
    players.get(currentPlayerIndex).onTurn(this);
  }

  public void onEndTurn() {
    checkWinCondition();

    if (currentPlayerIndex == players.size() - 1 && gameState == GameState.PLAYING) {
      System.out.println("\nVictory Point Standings:");
      displayVPStandings();

      if (currentTurn < turns) {
        currentTurn++;
        System.out.println("\n########## TURN " + currentTurn + " ###############");
      } else {
        System.out.println("Maximum turns reached. Game ending.");
        gameState = GameState.END;
      }
    }

    if (gameState == GameState.PLAYING) {
      currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
      Player nextPlayer = players.get(currentPlayerIndex);

      System.out.println("\n##### " + nextPlayer.getName() + "'s turn #####");

      generateResources();

    } else if (gameState == GameState.END) {
      displayResults();
    }
  }

  private void generateResources() {
    int roll = dice.rollDice(2);
    Player roller = players.get(currentPlayerIndex);
    System.out.println(roller.getName() + " rolled a " + roll);

    if (roll == 7) {
      System.out.println("A 7 was rolled! The Robber is striking.");
      Set<Player> stealablePlayers = board.moveRobberToRandomTile(rng);
      robPlayers(stealablePlayers);

    } else {
      board.notifyTilesOfRoll(roll);
    }
  }

  private void robPlayers(Set<Player> stealablePlayers) {
    Player roller = players.get(currentPlayerIndex);
    for (Player player : players) {
      if (player.getResourceCountTotal() > 7) {
        System.out.println(player.getName() + " has too many cards and loses half!");
        player.dropHalfResources(rng);
      }
    }

    Set<Player> temp = new HashSet<>();
    for (Player player : stealablePlayers) {
      if (player != roller && player.getResourceCountTotal() > 0) {
        temp.add(player);
      }
    }

    List<Player> stealablePlayersList = new ArrayList<>(temp);

    if (!stealablePlayersList.isEmpty()) {
      Player target = stealablePlayersList.get(rng.nextInt(stealablePlayersList.size()));
      Resource stolenResource = target.stealRandomResource(rng);

      if (stolenResource != null) {
        roller.addResource(stolenResource, 1);
        System.out.println(roller.getName() + " stole 1 " + stolenResource + " from " + target.getName());
      }
      
    } else {
      System.out.println("No one to steal from!");
    }
  }

  /**
   * Displays the final game results.
   */
  private void displayResults() {
    System.out.println("\nFinal Standings:");
    displayVPStandings();
  }

  private void displayVPStandings() {
    for (Player player : players) {
      int victoryPoints = player.getVictoryPoints();
      System.out.println(player.getName() + ": " + victoryPoints + " VP");
    }
  }

  private void checkWinCondition() {
    for (Player player : players) {
      if (player.getVictoryPoints() >= CatanSettings.WINNING_VP_COUNT) {
        gameState = GameState.END;
      }
    }
  }

  @Override
  public String toString() {
    return board.toString();
  }
}
