// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.game;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import com.team22.catan.structures.Structure;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	public enum PlayerColor {
		RED,
		BLUE,
		WHITE,
		ORANGE
	}

	/**
	 * 
	 */
	private final String playerName;
	private final PlayerColor color;
	private final EnumMap<Resource, Integer> inventory;
	private int victoryPoints;

	protected boolean diceRolled;

	public Player(String name, PlayerColor color) {
		playerName = name;
		this.color = color;
		inventory = new EnumMap<>(Resource.class);
		for (Resource resource : Resource.values()) {
			inventory.put(resource, 0);
		}

		diceRolled = false;
	}

	public String getName() {
		return playerName;
	}

	public PlayerColor getColor() {
		return color;
	}

	public Map<Resource, Integer> getInventory() {
		return new EnumMap<>(this.inventory);
	}

	public int getResource(Resource resource) {
		return inventory.get(resource);
	}

	public int getResourceCountTotal() {
		int total = 0;
		for (Resource resource : inventory.keySet()) {
			total += inventory.get(resource);
		}

		return total;
	}

	public int getVictoryPoints() {
		return victoryPoints;
	}

	public void addVictoryPoints(int n) {
		victoryPoints += n;
	}

	public void addResource(Resource resource, int number) {
		int value = inventory.get(resource) + number;
		if (value < 0) {
			throw new ArithmeticException("Can't have negative resources");
		}
		inventory.put(resource, value);
	}

	public boolean canAfford(Map<Resource, Integer> cost) {
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			Resource resource = entry.getKey();
			int requiredAmount = entry.getValue();

			int playerAmount = inventory.getOrDefault(resource, 0);

			if (playerAmount < requiredAmount) {
				return false;
			}
		}

		return true;
	}

	public void build(Structure structure) {
		Map<Resource, Integer> cost = structure.getCost();
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			Resource resource = entry.getKey();
			int required = entry.getValue();
			int current = inventory.get(resource);
			inventory.put(resource, current - required);
		}
	}

	@Override
	public String toString() {
		StringBuilder res = new StringBuilder();

		res.append(this.playerName);
		res.append("\nVP: ");
		res.append(victoryPoints);
		res.append("Resources: \n");
		for (Map.Entry<Resource, Integer> entry : this.inventory.entrySet()) {
			res.append("\t");
			res.append(entry.getKey());
			res.append(" : ");
			res.append(entry.getValue());
			res.append("\n");
		}

		return res.toString();
	}

	public void dropHalfResources(Random rng) {
		int totalResources = getResourceCountTotal();
		if (totalResources <= 7)
			return;

		int targetDropCount = totalResources / 2;
		int currentDrops = 0;

		while (currentDrops < targetDropCount) {
			List<Resource> availableResources = new ArrayList<>();
			for (Map.Entry<Resource, Integer> entry : inventory.entrySet()) {
				if (entry.getValue() > 0) {
					availableResources.add(entry.getKey());
				}
			}

			if (availableResources.isEmpty())
				break;

			Resource resourceToDrop = availableResources.get(rng.nextInt(availableResources.size()));
			inventory.put(resourceToDrop, inventory.get(resourceToDrop) - 1);
			currentDrops++;
		}
	}

	public Resource stealRandomResource(Random rng) {
		if (getResourceCountTotal() == 0)
			return null; // Nothing to steal

		List<Resource> availableCards = new ArrayList<>();
		for (Map.Entry<Resource, Integer> entry : inventory.entrySet()) {
			for (int i = 0; i < entry.getValue(); i++) {
				availableCards.add(entry.getKey());
			}
		}

		Resource stolen = availableCards.get(rng.nextInt(availableCards.size()));
		inventory.put(stolen, inventory.get(stolen) - 1);
		return stolen;
	}

	public void setDiceRolled(boolean diceRolled) {
		this.diceRolled = diceRolled;
	}

	public boolean getDiceRolled() {
		return diceRolled;
	}

	public abstract void onTurn(Game game);
}
