// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.game;

import java.util.EnumMap;
import java.util.Map;

import com.team22.catan.structures.Structure;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	private final String playerName;
	private final EnumMap<Resource, Integer> inventory;
	private int victoryPoints;

	public Player(String name) {
		playerName = name;
		inventory = new EnumMap<>(Resource.class);
		for (Resource resource : Resource.values()) {
			inventory.put(resource, 0);
		}
	}

	public String getName() {
		return playerName;
	}

	public Map<Resource, Integer> getInventory() {
		return new EnumMap<>(this.inventory);
	}

	public Integer getResource(Resource resource) {
		return inventory.get(resource);
	}

	public int getResourceCountTotal() {
		int total = 0;
		for (Resource resource : inventory.keySet()) {
			total += inventory.get(resource);
		}

		return total;
	}

	public int getVictoryPoints() {
		return victoryPoints;
	}

	public void addVictoryPoints(int n) {
		victoryPoints += n;
	}

	public void addResource(Resource resource, int number) {
		int value = inventory.get(resource) + number;
		if (value < 0) {
			throw new ArithmeticException("Can't have negative resources");
		}
		inventory.put(resource, value);
	}

	public boolean canAfford(Map<Resource, Integer> cost) {
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			Resource resource = entry.getKey();
			int requiredAmount = entry.getValue();

			int playerAmount = inventory.getOrDefault(resource, 0);

			if (playerAmount < requiredAmount) {
				return false;
			}
		}

		return true;
	}

	public void build(Structure structure) {
		Map<Resource, Integer> cost = structure.getCost();
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			Resource resource = entry.getKey();
			int required = entry.getValue();
			int current = inventory.get(resource);
			inventory.put(resource, current - required);
		}
	}

	@Override
	public String toString() {
		StringBuilder res = new StringBuilder();

		res.append(this.playerName);
		res.append("\nVP: ");
		res.append(victoryPoints);
		res.append("Resources: \n");
		for (Map.Entry<Resource, Integer> entry : this.inventory.entrySet()) {
			res.append("\t");
			res.append(entry.getKey());
			res.append(" : ");
			res.append(entry.getValue());
			res.append("\n");
		}

		return res.toString();
	}

	public abstract void onTurn(Game game);
}
