// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.team22.catan.board.AxialPosition.Direction;

/************************************************************/
/**
 * 
 */
public class Board {
	private Map<AxialPosition, Tile> tiles; // 19 Tiles
	private Map<NodePosition, Node> nodes; // 54 Nodes
	private Map<EdgePosition, Edge> edges; // 72 Edges

	private AxialPosition centre;
	private int size;
	private TileType[] boardLayout;
	private int[] tokenLayout;

	/**
	 * 
	 */
	public Board(TileType[] boardLayout, int[] tokenLayout) {
		tiles = new HashMap<>();
		nodes = new HashMap<>();
		edges = new HashMap<>();

		centre = new AxialPosition(0, 0);
		int numberOfTiles = Math.min(boardLayout.length, tokenLayout.length +
				Collections.frequency(Arrays.asList(boardLayout), TileType.DESERT));
		this.size = calculateRadius(numberOfTiles);
		this.boardLayout = Arrays.copyOf(boardLayout, numberOfTiles);
		this.tokenLayout = Arrays.copyOf(tokenLayout, numberOfTiles);

		addTiles();
	}

	private int calculateRadius(int numberOfTiles) {
		return (int) Math.ceil(Math.round(
				((1f/6f) * Math.sqrt(12f * numberOfTiles - 3f) - 0.5f) * 1000f) / 1000f);
	}

	private void addTiles() {
		int tokenIndex = 0, tileIndex = 0;

		for (AxialPosition position : getOrderedTilePositions()) {
			addTile(position, tokenLayout[tokenIndex], boardLayout[tileIndex]);
			if (boardLayout[tileIndex] != TileType.DESERT) {
				tokenIndex++;
			}

			tileIndex++;
		}
	}

	private void addTile(AxialPosition position, int token, TileType type) {
		if (type == TileType.DESERT) {
			token = 0;
		}

		Tile tile = new Tile(position, token, type);
		assignNodesToTile(tile);
		assignEdgesToTile(tile);

		for (EdgePosition edgePosition : tile.borders()) {
			Edge edge = tile.getEdge(edgePosition);
			Node startNode = nodes.get(edge.endpoints().get(0));
			Node endNode = nodes.get(edge.endpoints().get(1));
			edge.setNodes(startNode, endNode);

			if (!startNode.getEdges().contains(edge)) {
				startNode.addEdge(edge);
			}

			if (!endNode.getEdges().contains(edge)) {
				endNode.addEdge(edge);
			}
		}

		tiles.put(position, tile);
	}

	private void assignNodesToTile(Tile tile) {
		List<NodePosition> tileNodePositions = tile.corners();

		for (NodePosition nodePosition : tileNodePositions) {
			if (!nodes.containsKey(nodePosition)) {
				Node nodeToBeAdded = new Node(nodePosition);
				tile.addNode(nodeToBeAdded);
				nodes.put(nodePosition, nodeToBeAdded);
			} else {
				tile.addNode(nodes.get(nodePosition));
			}
		}
	}

	private void assignEdgesToTile(Tile tile) {
		List<EdgePosition> tileEdgePositions = tile.borders();

		for (EdgePosition edgePosition : tileEdgePositions) {
			if (!edges.containsKey(edgePosition)) {
				Edge edgeToBeAdded = new Edge(edgePosition);
				tile.addEdge(edgeToBeAdded);
				edges.put(edgePosition, edgeToBeAdded);
			} else {
				tile.addEdge(edges.get(edgePosition));
			}
		}
	}

	public Map<AxialPosition, Tile> getTiles() {
		return new HashMap<AxialPosition, Tile>(tiles);
	}

	public Map<NodePosition, Node> getNodes() {
		return new HashMap<NodePosition, Node>(nodes);
	}

	public Map<EdgePosition, Edge> getEdges() {
		return new HashMap<EdgePosition, Edge>(edges);
	}

	public void notifyTilesOfRoll(int roll) {
		for (Tile tile : tiles.values()) {
			tile.generateResource(roll);
		}
	}

	public List<Tile> getOrderedTiles() {
		List<Tile> orderedTiles = new ArrayList<>();
		for (AxialPosition position : getOrderedTilePositions()) {
			orderedTiles.add(tiles.get(position));
		}

		return orderedTiles;
	}

	private List<AxialPosition> getOrderedTilePositions() {
		List<AxialPosition> orderedPositions = new ArrayList<>();
		orderedPositions.add(centre);
		for (int ring = 1; ring <= size; ring++) {
			AxialPosition currentTilePosition = centre.add(Direction.DOWNLEFT.getVector().scale(ring));
			for (int i = 0; i < 6; i++) {
				for (int j = 0; j < ring; j++) {
					orderedPositions.add(currentTilePosition);
					// Enum is laid out such that indexing Direction.values()[i] will be correct
					currentTilePosition = currentTilePosition.neighbour(Direction.values()[i]);
				}
			}
		}

		return orderedPositions;
	}

	/**
	 * 
	 * @return
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		for (Tile tile : getOrderedTiles()) {
			sb.append("(" + tile + ", " + tile.getPosition() + ", " + tile.getToken() + ")\n");
		}

		return sb.toString();
	}
}
