// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.team22.catan.board.AxialPosition.Direction;

/************************************************************/
/**
 * 
 */
public class Board {
	private Map<AxialPosition, Tile> tiles; // 19 Tiles
	private Map<NodePosition, Node> nodes; // 54 Nodes
	private Map<EdgePosition, Edge> edges; // 72 Edges

	private AxialPosition centre;
	private int size;
	private TileType[] boardLayout;
	private int[] tokenLayout;

	/**
	 * 
	 */
	public Board(TileType[] boardLayout, int[] tokenLayout) {
		tiles = new HashMap<>();
		nodes = new HashMap<>();
		edges = new HashMap<>();

		centre = new AxialPosition(0, 0);
		int numberOfTiles = Math.min(boardLayout.length, tokenLayout.length +
				Collections.frequency(Arrays.asList(boardLayout), TileType.DESERT));
		this.size = calculateRadius(numberOfTiles);
		this.boardLayout = Arrays.copyOf(boardLayout, numberOfTiles);
		this.tokenLayout = Arrays.copyOf(tokenLayout, numberOfTiles);

		addTiles();
	}

	private int calculateRadius(int numberOfTiles) {
		return (int) Math.ceil(Math.round(
				((1f/6f) * Math.sqrt(12f * numberOfTiles - 3f) - 0.5f) * 1000f) / 1000f);
	}

	private void addTiles() {
		int tokenIndex = 0, tileIndex = 0;

		for (AxialPosition position : getOrderedTilePositions()) {
			addTile(position, tokenLayout[tokenIndex], boardLayout[tileIndex]);
			if (boardLayout[tileIndex] != TileType.DESERT) {
				tokenIndex++;
			}

			tileIndex++;
		}
	}

	private void addTile(AxialPosition position, int token, TileType type) {
		if (type == TileType.DESERT) {
			token = 0;
		}

		Tile tile = new Tile(position, token, type);
		assignNodesToTile(tile);
		assignEdgesToTile(tile);

		for (EdgePosition edgePosition : tile.borders()) {
			Edge edge = tile.getEdge(edgePosition);
			Node startNode = nodes.get(edge.endpoints().get(0));
			Node endNode = nodes.get(edge.endpoints().get(1));
			edge.setNodes(startNode, endNode);

			if (!startNode.getEdges().contains(edge)) {
				startNode.addEdge(edge);
			}

			if (!endNode.getEdges().contains(edge)) {
				endNode.addEdge(edge);
			}
		}

		tiles.put(position, tile);
	}

	private void assignNodesToTile(Tile tile) {
		List<NodePosition> tileNodePositions = tile.corners();

		for (NodePosition nodePosition : tileNodePositions) {
			if (!nodes.containsKey(nodePosition)) {
				Node nodeToBeAdded = new Node(nodePosition);
				tile.addNode(nodeToBeAdded);
				nodes.put(nodePosition, nodeToBeAdded);
			} else {
				tile.addNode(nodes.get(nodePosition));
			}
		}
	}

	private void assignEdgesToTile(Tile tile) {
		List<EdgePosition> tileEdgePositions = tile.borders();

		for (EdgePosition edgePosition : tileEdgePositions) {
			if (!edges.containsKey(edgePosition)) {
				Edge edgeToBeAdded = new Edge(edgePosition);
				tile.addEdge(edgeToBeAdded);
				edges.put(edgePosition, edgeToBeAdded);
			} else {
				tile.addEdge(edges.get(edgePosition));
			}
		}
	}

	public Map<AxialPosition, Tile> getTiles() {
		return new HashMap<AxialPosition, Tile>(tiles);
	}

	public Map<NodePosition, Node> getNodes() {
		return new HashMap<NodePosition, Node>(nodes);
	}

	public Map<EdgePosition, Edge> getEdges() {
		return new HashMap<EdgePosition, Edge>(edges);
	}

	public void notifyTilesOfRoll(int roll) {
		for (Tile tile : tiles.values()) {
			tile.generateResource(roll);
		}
	}

	public List<Tile> getOrderedTiles() {
		List<Tile> orderedTiles = new ArrayList<>();
		for (AxialPosition position : getOrderedTilePositions()) {
			orderedTiles.add(tiles.get(position));
		}

		return orderedTiles;
	}

	private List<AxialPosition> getOrderedTilePositions() {
		List<AxialPosition> orderedPositions = new ArrayList<>();
		orderedPositions.add(centre);
		for (int ring = 1; ring <= size; ring++) {
			AxialPosition currentTilePosition = centre.add(Direction.DOWNLEFT.getVector().scale(ring));
			for (int i = 0; i < 6; i++) {
				for (int j = 0; j < ring; j++) {
					orderedPositions.add(currentTilePosition);
					// Enum is laid out such that indexing Direction.values()[i] will be correct
					currentTilePosition = currentTilePosition.neighbour(Direction.values()[i]);
				}
			}
		}

		return orderedPositions;
	}

    private static final NodePosition[] NODE_ID_TO_POSITION = {
            new NodePosition(0, -3, RelativeNodeLocation.SOUTH),  // 0
            new NodePosition(0, -2, RelativeNodeLocation.NORTH),  // 1
            new NodePosition(1, -3, RelativeNodeLocation.SOUTH),  // 2
            new NodePosition(1, -2, RelativeNodeLocation.NORTH),  // 3
            new NodePosition(2, -3, RelativeNodeLocation.SOUTH),  // 4
            new NodePosition(2, -2, RelativeNodeLocation.NORTH),  // 5
            new NodePosition(3, -3, RelativeNodeLocation.SOUTH),  // 6

            new NodePosition(-1, -2, RelativeNodeLocation.SOUTH), // 7
            new NodePosition(-1, -1, RelativeNodeLocation.NORTH), // 8
            new NodePosition(0, -2, RelativeNodeLocation.SOUTH),  // 9
            new NodePosition(0, -1, RelativeNodeLocation.NORTH),  // 10
            new NodePosition(1, -2, RelativeNodeLocation.SOUTH),  // 11
            new NodePosition(1, -1, RelativeNodeLocation.NORTH),  // 12
            new NodePosition(2, -2, RelativeNodeLocation.SOUTH),  // 13
            new NodePosition(2, -1, RelativeNodeLocation.NORTH),  // 14
            new NodePosition(3, -2, RelativeNodeLocation.SOUTH),  // 15

            new NodePosition(-2, -1, RelativeNodeLocation.SOUTH), // 16
            new NodePosition(-2, 0, RelativeNodeLocation.NORTH),  // 17
            new NodePosition(-1, -1, RelativeNodeLocation.SOUTH), // 18
            new NodePosition(-1, 0, RelativeNodeLocation.NORTH),  // 19
            new NodePosition(0, -1, RelativeNodeLocation.SOUTH),  // 20
            new NodePosition(0, 0, RelativeNodeLocation.NORTH),   // 21
            new NodePosition(1, -1, RelativeNodeLocation.SOUTH),  // 22
            new NodePosition(1, 0, RelativeNodeLocation.NORTH),   // 23
            new NodePosition(2, -1, RelativeNodeLocation.SOUTH),  // 24
            new NodePosition(2, 0, RelativeNodeLocation.NORTH),   // 25
            new NodePosition(3, -1, RelativeNodeLocation.SOUTH),  // 26

            new NodePosition(-3, 1, RelativeNodeLocation.NORTH),  // 27
            new NodePosition(-2, 0, RelativeNodeLocation.SOUTH),  // 28
            new NodePosition(-2, 1, RelativeNodeLocation.NORTH),  // 29
            new NodePosition(-1, 0, RelativeNodeLocation.SOUTH),  // 30
            new NodePosition(-1, 1, RelativeNodeLocation.NORTH),  // 31
            new NodePosition(0, 0, RelativeNodeLocation.SOUTH),   // 32
            new NodePosition(0, 1, RelativeNodeLocation.NORTH),   // 33
            new NodePosition(1, 0, RelativeNodeLocation.SOUTH),   // 34
            new NodePosition(1, 1, RelativeNodeLocation.NORTH),   // 35
            new NodePosition(2, 0, RelativeNodeLocation.SOUTH),   // 36
            new NodePosition(2, 1, RelativeNodeLocation.NORTH),   // 37

            new NodePosition(-3, 2, RelativeNodeLocation.NORTH),  // 38
            new NodePosition(-2, 1, RelativeNodeLocation.SOUTH),  // 39
            new NodePosition(-2, 2, RelativeNodeLocation.NORTH),  // 40
            new NodePosition(-1, 1, RelativeNodeLocation.SOUTH),  // 41
            new NodePosition(-1, 2, RelativeNodeLocation.NORTH),  // 42
            new NodePosition(0, 1, RelativeNodeLocation.SOUTH),   // 43
            new NodePosition(0, 2, RelativeNodeLocation.NORTH),   // 44
            new NodePosition(1, 1, RelativeNodeLocation.SOUTH),   // 45
            new NodePosition(1, 2, RelativeNodeLocation.NORTH),   // 46

            new NodePosition(-3, 3, RelativeNodeLocation.NORTH),  // 47
            new NodePosition(-2, 2, RelativeNodeLocation.SOUTH),  // 48
            new NodePosition(-2, 3, RelativeNodeLocation.NORTH),  // 49
            new NodePosition(-1, 2, RelativeNodeLocation.SOUTH),  // 50
            new NodePosition(-1, 3, RelativeNodeLocation.NORTH),  // 51
            new NodePosition(0, 2, RelativeNodeLocation.SOUTH),   // 52
            new NodePosition(0, 3, RelativeNodeLocation.NORTH)    // 53
    };

    /**
     * Translates an integer Node ID from the human command line
     * into the corresponding NodePosition using an array lookup.
     */
    public NodePosition getNodePositionFromId(int id) {
        if (id >= 0 && id < NODE_ID_TO_POSITION.length) {
            return NODE_ID_TO_POSITION[id];
        }
        return null;
    }

    public EdgePosition getEdgePositionFromNodes(NodePosition n1, NodePosition n2) {
        for (Edge edge : edges.values()) {
            List<NodePosition> endpoints = edge.endpoints();

            if (endpoints.contains(n1) && endpoints.contains(n2)) {
                return edge.getPosition();
            }
        }
        return null;
    }

	/**
	 * 
	 * @return
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		for (Tile tile : getOrderedTiles()) {
			sb.append("(" + tile + ", " + tile.getPosition() + ", " + tile.getToken() + ")\n");
		}

		return sb.toString();
	}
}
