// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.ArrayList;
import java.util.List;

import com.team22.catan.game.Player;
import com.team22.catan.structures.Road;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Road road;
	private EdgePosition position;
	private Node startNode;
	private Node endNode;

	/**
	 * 
	 */
	public Edge(EdgePosition position) {
		this.position = position;
		road = null;
		startNode = null;
		endNode = null;
	}

	public List<NodePosition> endpoints() {
		List<NodePosition> endNodes = new ArrayList<>();
		switch (position.getRelativeLocation()) {
			case NORTHEAST:
				endNodes.add(new NodePosition(
					position.getQ() + 1, position.getR() - 1, RelativeNodeLocation.SOUTH));
				endNodes.add(new NodePosition(
					position.getQ(), position.getR(), RelativeNodeLocation.NORTH));
				break;
			
			case NORTHWEST:
				endNodes.add(
					new NodePosition(position.getQ(), position.getR(), RelativeNodeLocation.NORTH));
				endNodes.add(
					new NodePosition(position.getQ(), position.getR() - 1, RelativeNodeLocation.SOUTH));
				break;

			case WEST:
				endNodes.add(
					new NodePosition(position.getQ(), position.getR() - 1, RelativeNodeLocation.SOUTH));
				endNodes.add(
					new NodePosition(position.getQ() - 1, position.getR() + 1, RelativeNodeLocation.NORTH));
				break;
		}
		
		return endNodes;
	}

	public Node getStartNode() {
		return startNode;
	}

	public Node getEndNode() {
		return endNode;
	}

	public void setNodes(Node startNode, Node endNode) {
		this.startNode = startNode;
		this.endNode = endNode;
	}

	public EdgePosition getPosition() {
		return position;
	}

	public boolean hasRoad() {
		return road != null;
	}

	public boolean canPlaceRoad(Player player) {
		if ((startNode.hasStructure() && startNode.getStructure().getOwner().equals(player)) ||
				(endNode.hasStructure() && endNode.getStructure().getOwner().equals(player))) {
			return true;
		}

		for (Edge edge : startNode.getEdges()) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				return true;
			}
		}
		
		for (Edge edge : endNode.getEdges()) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				return true;
			}
		}

		return false;
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
		if (canPlaceRoad(road.getOwner())) {
			this.road = road;
		} else {
			throw new IllegalStateException("Cannot place road at " + position);
		}
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
		return road;
	}

	@Override
	public String toString() {
		return position.toString();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj == null || getClass() != obj.getClass()) {
			return false;
		}

		Edge otherEdge = (Edge) obj;
		if (position.getQ() == otherEdge.getPosition().getQ() &&
				position.getR() == otherEdge.getPosition().getR() &&
				position.getRelativeLocation() == otherEdge.getPosition().getRelativeLocation()) {
			return true;
		} else {
			return false;
		}
	}
}
