// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.Stack;

import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;
import com.team22.catan.structures.Road;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Road road;
	private EdgePosition position;
	private Node startNode;
	private Node endNode;

	/**
	 * 
	 */
	public Edge(EdgePosition position) {
		this.position = position;
		road = null;
		startNode = null;
		endNode = null;
	}

	public List<NodePosition> endpoints() {
		return position.endpoints();
	}

	public Node getStartNode() {
		return startNode;
	}

	public Node getEndNode() {
		return endNode;
	}

	public void setNodes(Node startNode, Node endNode) {
		this.startNode = startNode;
		this.endNode = endNode;
	}

	public EdgePosition getPosition() {
		return position;
	}

	public boolean hasRoad() {
		return road != null;
	}

	public boolean canPlaceRoad(Player player, GameState gameState) {
		if (hasRoad()) {
			return false;
		}

		if (gameState == GameState.SETUP) {
			for (Edge edge : startNode.getEdges()) {
				if (edge.hasRoad() && !endNode.hasStructure()) {
					return false;
				}
			}

			for (Edge edge : endNode.getEdges()) {
				if (edge.hasRoad() && !startNode.hasStructure()) {
					return false;
				}
			}
		}

		if ((startNode.hasStructure() && startNode.getStructure().getOwner().equals(player)) ||
				(endNode.hasStructure() && endNode.getStructure().getOwner().equals(player))) {
			return true;
		}

		for (Edge edge : startNode.getEdges()) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				return true;
			}
		}

		for (Edge edge : endNode.getEdges()) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				return true;
			}
		}

		return false;
	}

	/**
	 * 
	 * @param road
	 */
	public void placeRoad(Road road, GameState gameState) {
		if (canPlaceRoad(road.getOwner(), gameState)) {
			this.road = road;
		} else {
			throw new IllegalStateException("Cannot place road at " + position);
		}
	}

	public Road removeRoad() {
		if (hasRoad()) {
			Road previousRoad = road;
			road = null;
			return previousRoad;
		} else {
			throw new NoSuchElementException("No road currently on edge " + position);
		}
	}

	/**
	 * 
	 * @return
	 */
	public Road getRoad() {
		return road;
	}

  /**
   * Gets the longest road starting from this edge via a depth first search
   * 
   * Algorithm adapted from:
   * https://github.com/seansegal/tincisnotcatan/blob/master/src/main/java/edu/brown/cs/board/Path.java
   * 
   * @return the length of the longest road
    */
  public int getLongestRoad(Player player) {
    Set<Edge> visited = new HashSet<>();
    Stack<Edge> toVist = new Stack<>();
    Map<Edge, Integer> lengths = new HashMap<>();

    toVist.push(this);
    lengths.put(this, 0);
    while (!toVist.isEmpty()) {
      Edge currentEdge = toVist.pop();
      int currentLength = lengths.get(currentEdge);
      visited.add(currentEdge);
      for (Edge edge : currentEdge.getStartNode().getEdges()) {
        if (edge.hasRoad() && edge.getRoad().getOwner().equals(player) &&
            !visited.contains(edge) && (!currentEdge.getStartNode().hasStructure() ||
            currentEdge.getStartNode().getStructure().getOwner().equals(player))) {
          toVist.push(edge);
          lengths.put(edge, currentLength + 1);
        }
      }

      for (Edge edge : currentEdge.getEndNode().getEdges()) {
        if (edge.hasRoad() && edge.getRoad().getOwner().equals(player) &&
            !visited.contains(edge) && (!currentEdge.getEndNode().hasStructure() ||
            currentEdge.getEndNode().getStructure().getOwner().equals(player))) {
          toVist.push(edge);
          lengths.put(edge, currentLength + 1);
        }
      }
    }

    int maxLength = 0;
    for (Edge edge : visited) {
      int length = lengths.get(edge);
      if (length > maxLength) {
        maxLength = length;
      }
    }

    return maxLength;
  }

	@Override
	public String toString() {
		return position.toString();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj == null || getClass() != obj.getClass()) {
			return false;
		}

		Edge otherEdge = (Edge) obj;
		if (position.getQ() == otherEdge.getPosition().getQ() &&
				position.getR() == otherEdge.getPosition().getR() &&
				position.getRelativeLocation() == otherEdge.getPosition().getRelativeLocation()) {
			return true;
		} else {
			return false;
		}
	}
}
