// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;

import com.team22.catan.game.GameState;
import com.team22.catan.game.Player;
import com.team22.catan.game.Resource;
import com.team22.catan.structures.City;
import com.team22.catan.structures.Settlement;
import com.team22.catan.structures.SettlementStructure;

/************************************************************/
/**
 * 
 */
public class Node {
	private List<Edge> edges;
	private NodePosition position;
	private SettlementStructure structure;
	/**
	 * 
	 */
	public Node(NodePosition position) {
		this.position = position;
		structure = null;

		edges = new ArrayList<>();
	}

	public Node(int q, int r, RelativeNodeLocation location, List<Edge> edges) {
		this.position = new NodePosition(q, r, location);
		structure = null;

		this.edges = edges;
	}

	public List<EdgePosition> protrudes() {
		List<EdgePosition> protrudingEdgePositions = new ArrayList<>();
		switch (position.getRelativeLocation()) {
			case NORTH:
				protrudingEdgePositions.add(new EdgePosition(
						position.getQ() + 1, position.getR() -1, RelativeEdgeLocation.WEST));
				protrudingEdgePositions.add(new EdgePosition(
						position.getQ(), position.getR(), RelativeEdgeLocation.NORTHWEST));
				protrudingEdgePositions.add(
						new EdgePosition(position.getQ(), position.getR(), RelativeEdgeLocation.NORTHEAST));
				break;

			case SOUTH:
				protrudingEdgePositions.add(new EdgePosition(
						position.getQ(), position.getR(), RelativeEdgeLocation.NORTHWEST));
				protrudingEdgePositions.add(new EdgePosition(
						position.getQ() - 1, position.getR() + 1, RelativeEdgeLocation.NORTHEAST));
				protrudingEdgePositions.add(new EdgePosition(
						position.getQ(), position.getR() + 1, RelativeEdgeLocation.WEST));
				break;
		}

		return protrudingEdgePositions;
	}

	public void notifyStructureOfResource(Resource resource) {
    if (!hasStructure()) {
      throw new NoSuchElementException("No structure on node " + position);
    }

    structure.giveResourceToPlayer(resource);
		System.out.println(structure.getOwner().getName() + " recieved " + structure.getVP() + " " +
				resource.toString().toLowerCase());
	}

	public boolean hasStructure() {
		return structure != null;
	}

	public boolean hasSettlement() {
		return structure instanceof Settlement;
	}

	public boolean hasCity() {
		return structure instanceof City;
	}

	public boolean canPlaceSettlement(Player player, GameState gameState) {
		if (structure != null) {
			return false;
		}

		if (gameState == GameState.SETUP) {
			return distanceRule();
		}

		boolean connectedRoad = false;
		for (Edge edge : edges) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				connectedRoad = true;
			}
		}

		if (!connectedRoad) {
			return false;
		}

		// Distance rule
		return distanceRule();
	}

	public boolean distanceRule() {
		boolean distanceRule = true;
		for (Edge edge : edges) {
			Node otherNode;
			if (edge.getStartNode().equals(this)) {
				otherNode = edge.getEndNode();
			} else {
				otherNode = edge.getStartNode();
			}

			if (otherNode.hasStructure()) {
				distanceRule = false;
			}
		}

		return distanceRule;
	}

	public boolean canPlaceCity(Player player, GameState gameState) {
		if (structure == null || gameState != GameState.PLAYING) {
			return false;
		}

		if (structure instanceof Settlement && structure.getOwner().equals(player)) {
			return true;
		}

		return false;
	}

	public void placeSettlement(Settlement settlement, GameState gameState) {
		if (canPlaceSettlement(settlement.getOwner(), gameState)) {
			this.structure = settlement;
		} else {
			throw new IllegalStateException("Cannot place settlement at " + position);
		}
	}

	public Settlement removeSettlement() {
		if (hasSettlement()) {
			Settlement settlement = (Settlement) structure;
			structure = null;
			return settlement;
		} else {
			throw new NoSuchElementException("No settlement currently on node " + position);
		}
	}

	public void placeCity(City city, GameState gameState) {
		if (canPlaceCity(city.getOwner(), gameState)) {
			this.structure = city;
		} else {
			throw new IllegalStateException("Cannot place city at " + position);
		}
	}

	public City removeCity() {
		if (hasCity()) {
			City city = (City) structure;
			structure = new Settlement(city.getOwner());
			return city;
		} else {
			throw new NoSuchElementException("No city currently on node " + position);
		}
	}

	public void addEdge(Edge edge) {
		if (edges.size() >= 3) {
			throw new IllegalStateException("Node cannot have more than 3 edges");
		}

		edges.add(edge);
	}

	public List<Edge> getEdges() {
		return new ArrayList<>(edges);
	}

	public NodePosition getPosition() {
		return position;
	}

	/**
	 * 
	 * @return 
	 */
	public SettlementStructure getStructure() {
		return structure;
	}

	/**
	 * 
	 *
	 */
	public String toString() {
		if (structure != null) {
			return structure.toString();
		} else {
			return "Empty Node";
		}
	}
}
