// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.Objects;

/************************************************************/
/**
 * 
 */
public class NodePosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;
	private RelativeNodeLocation location;

	public NodePosition(int q, int r, RelativeNodeLocation location) {
		this.q = q;
		this.r = r;
		this.location = location;
	}

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
		return q;
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
		return r;
	}

	/**
	 * 
	 * @return 
	 */
	public RelativeNodeLocation getRelativeLocation() {
		return location;
	}

	/**
	 * 
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj == null) {
			return false;
		}

		if (getClass() != obj.getClass()) {
			return false;
		}

		NodePosition otherPos = (NodePosition) obj;
		if (q == otherPos.getQ() && r == otherPos.getR() && location == otherPos.getRelativeLocation()) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public int hashCode() {
			return Objects.hash(q, r, getRelativeLocation());
	}

	@Override
	public String toString() {
		return "(" + q + ", " + r + ", " + location + ")";
	}
}
