// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

/************************************************************/
/**
 * 
 */
public enum RelativeEdgeLocation {
	/**
	 * 
	 */
	WEST,
	/**
	 * 
	 */
	NORTHWEST,
	/**
	 * 
	 */
	NORTHEAST;
}
