// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.team22.catan.board;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.team22.catan.game.Player;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private TileType tileType;
	public boolean hasRobber = false;
	/**
	 * 
	 */
	private int numberTokenValue;
	private AxialPosition position;
	private Map<NodePosition, Node> intersections;
	private Map<EdgePosition, Edge> edges;

	/**
	 * 
	 * @param token
	 * @param type
	 * @param nodes
	 */
	public Tile(AxialPosition position, int token, TileType type) {
		this.position = position;
		numberTokenValue = token;
		tileType = type;

		intersections = new HashMap<>();
		edges = new HashMap<>();
	}

	public void addNode(Node node) {
		if (intersections.size() >= 6) {
			throw new IllegalStateException("Tile cannot have more than 6 nodes");
		}

		intersections.put(node.getPosition(), node);
	}

	public void addEdge(Edge edge) {
		if (edges.size() >= 6) {
			throw new IllegalStateException("Tile cannot have more than 6 edges");
		}

		edges.put(edge.getPosition(), edge);
	}

	public List<NodePosition> corners() {
		List<NodePosition> cornerNodePositions = new ArrayList<>();
			cornerNodePositions.add(
				new NodePosition(position.getQ(), position.getR(), RelativeNodeLocation.NORTH));
		cornerNodePositions.add(
				new NodePosition(position.getQ() + 1, position.getR() - 1, RelativeNodeLocation.SOUTH));
		cornerNodePositions.add(
				new NodePosition(position.getQ(), position.getR() + 1, RelativeNodeLocation.NORTH));
		cornerNodePositions.add(
				new NodePosition(position.getQ(), position.getR(), RelativeNodeLocation.SOUTH));
		cornerNodePositions.add(
				new NodePosition(position.getQ() - 1, position.getR() + 1, RelativeNodeLocation.NORTH));
		cornerNodePositions.add(
				new NodePosition(position.getQ(), position.getR() - 1, RelativeNodeLocation.SOUTH));

		return cornerNodePositions;
	}

	public List<EdgePosition> borders() {
		List<EdgePosition> borderEdgePositions = new ArrayList<>();
		borderEdgePositions.add(
				new EdgePosition(position.getQ() + 1, position.getR(), RelativeEdgeLocation.WEST));
		borderEdgePositions.add(
				new EdgePosition(position.getQ(), position.getR(), RelativeEdgeLocation.NORTHEAST));
		borderEdgePositions.add(
				new EdgePosition(position.getQ(), position.getR(), RelativeEdgeLocation.NORTHWEST));
		borderEdgePositions.add(
				new EdgePosition(position.getQ(), position.getR(), RelativeEdgeLocation.WEST));
		borderEdgePositions.add(
				new EdgePosition(position.getQ() - 1, position.getR() + 1, RelativeEdgeLocation.NORTHEAST));
		borderEdgePositions.add(
				new EdgePosition(position.getQ(), position.getR() + 1, RelativeEdgeLocation.NORTHWEST));

		return borderEdgePositions;
	}

	public void generateResource(int roll) {
		// ADDED: !hasRobber check
		if (roll == numberTokenValue && !hasRobber) {
			for (Node node : intersections.values()) {
				if (node.hasStructure()) {
					node.notifyStructureOfResource(tileType.getProducedResource());
				}
			}
		}
	}

	public void setRobber(boolean hasRobber) {
		this.hasRobber = hasRobber;
	}

	public boolean hasRobber() {
		return hasRobber;
	}

	public Set<Player> playersOnSurroundingNodes() {
		Set<Player> players = new HashSet<>();
		for (Node node : intersections.values()) {
			if (node.hasStructure()) {
				players.add(node.getStructure().getOwner());
			}
		}

		return players;
	}

	public AxialPosition getPosition() {
		return position;
	}

	/**
	 * 
	 * @return
	 */
	public TileType getTileType() {
		return tileType;
	}

	/**
	 * 
	 * @return
	 */
	public int getToken() {
		return numberTokenValue;
	}

	/**
	 * 
	 * @return
	 */
	public Node getNode(NodePosition nodePosition) {
		return intersections.get(nodePosition);
	}

	public Edge getEdge(EdgePosition edgePosition) {
		return edges.get(edgePosition);
	}

	/**
	 * 
	 * @return
	 */
	public String toString() {
		return tileType.toString();
	}
}
