// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public interface Action {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public undef Property1;

	/**
	 * 
	 */
	public void execute();
}
