// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.NodePosition;
import game.Player;
import structures.Settlement;

/************************************************************/
/**
 * 
 */
public class BuildSettlement implements Action {
	private Player player;
	private Board board;
	private NodePosition nodePosition;

	/**
	 * 
	 */
	public BuildSettlement(Player player, Board board, NodePosition nodePosition) {
		this.player = player;
    this.board = board;
    this.nodePosition = nodePosition;
	}

	/**
	 * 
	 */
	@Override
	public void execute() {
    Settlement settlement = new Settlement(player);
    if (!player.canAfford(settlement.getCost())) {
			System.out.println(player.getName() +
					" attempted to build a new settlement but could not afford it.");
		} else if (!board.getNodes().get(nodePosition).canPlaceSettlement(player)) {
			System.out.println(player.getName() + " attempted to build a new settlement but failed.");
		} else {
			player.build(settlement);
			board.getNodes().get(nodePosition).placeSettlement(settlement);
		}
	}
}
