// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.Node;
import board.NodePosition;
import game.Player;
import structures.City;
import structures.Settlement;

/************************************************************/
/**
 * 
 */
public class BuildSettlement implements Action {
	private Player player;
	private Board board;
	private NodePosition nodePosition;

	/**
	 * 
	 */
	public BuildSettlement(Player player, Board board, NodePosition nodePosition) {

        execute();
	}

	/**
	 * 
	 */
	@Override
	public void execute() {

        Settlement newSettlement = new Settlement(player);
        Node currentNode = board.getCorrespondingNode(nodePosition);

        currentNode.setStructure(newSettlement);
	}
}
