// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.Edge;
import board.EdgePosition;
import game.Player;
import structures.Road;

/************************************************************/
/**
 * 
 */
public class BuildRoad implements Action {
	private Player player;
	private Board board;
	private EdgePosition edgePosition;

	/**
	 * 
	 */
	public BuildRoad(Player player, Board board, EdgePosition edgePosition) {
	}

	/**
	 * 
	 */
	@Override
	public void execute() {

        Road newRoad = new Road(player);
        Edge currentEdge = board.getEdge(edgePosition);

        currentEdge.placeRoad(newRoad);
	}
}
