// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.NodePosition;
import game.Player;

/************************************************************/
/**
 * 
 */
public class BuildCity implements Action {
	private Player player;
	private Board board;
	private NodePosition nodePosition;
	/**
	 * 
	 */
	public BuildCity(Player player, Board board, NodePosition nodePosition) {
	}

	/**
	 * 
	 */
	public void execute() {
	}
}
