// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.Node;
import board.NodePosition;
import game.Player;
import structures.City;

/************************************************************/
/**
 * 
 */
public class BuildCity implements Action {
	private Player player;
	private Board board;
	private NodePosition nodePosition;
	/**
	 * 
	 */
	public BuildCity(Player player, Board board, NodePosition nodePosition) {

        execute();
    }

	/**
	 * 
	 */
	@Override
	public void execute() {

        City newCity = new City(player);
        Node currentNode = board.getCorrespondingNode(nodePosition);

        currentNode.setStructure(newCity);
	}
}
