// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import board.EdgePosition;
import game.Player;

/************************************************************/
/**
 * 
 */
public class BuildRoad implements Action {
	private Player player;
	private Board board;
	private EdgePosition edgePosition;

	/**
	 * 
	 */
	public BuildRoad(Player player, Board board, EdgePosition edgePosition) {
	}

	/**
	 * 
	 */
	@Override
	public void execute() {
	}
}
