// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import game.Game;
import game.Player;

/************************************************************/
/**
 * 
 */
public class EndTurn implements Action {
	private Player player;
	private Game game;
	/**
	 * 
	 */
	public EndTurn(Player player, Game game) {
	}

	/**
	 * 
	 */
	public void execute() {
	}
}
