// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class EndTurn implements Action {
	/**
	 * 
	 */
	public void EndTurn() {
	}

	/**
	 * 
	 */
	public void execute() {
	}
}
