// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import board.Board;
import game.Game;

/************************************************************/
/**
 * 
 */
public class GenerateResources implements Action {
	private Game game;
	/**
	 * 
	 */
	public GenerateResources(Game game) {
	}

	/**
	 * 
	 */
	@Override
	public void execute() {

        Board currentBoard = game.getBoard();

        //Adds calling dice rolls etc etc..


	}
}
