// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package actions;

import game.Game;

/************************************************************/
/**
 * 
 */
public class GenerateResources implements Action {
	private Game game;
	/**
	 * 
	 */
	public GenerateResources(Game game) {
	}

	/**
	 * 
	 */
	@Override
	public void execute() {


	}
}
