// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.board;

import java.util.Objects;

/************************************************************/
/**
 * 
 */
public class EdgePosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;
	private RelativeEdgeLocation location;

	public EdgePosition(int q, int r, RelativeEdgeLocation location) {
		this.q = q;
		this.r = r;
		this.location = location;
	}

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
		return q;
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
		return r;
	}

	/**
	 * 
	 * @return 
	 */
	public RelativeEdgeLocation getRelativeLocation() {
		return location;
	}

	@Override
	public String toString() {
		return "(" + q + ", " + r + ", " + location + ")";
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj == null) {
			return false;
		}

		if (getClass() != obj.getClass()) {
			return false;
		}

		EdgePosition otherPos = (EdgePosition) obj;
		if (q == otherPos.getQ() && r == otherPos.getR() && location == otherPos.getRelativeLocation()) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return Objects.hash(q, r, getRelativeLocation());
	}
}
