// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.board;

/************************************************************/
/**
 * 
 */
public enum RelativeEdgeLocation {
	/**
	 * 
	 */
	WEST,
	/**
	 * 
	 */
	NORTHWEST,
	/**
	 * 
	 */
	NORTHEAST;
}
