// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

/************************************************************/
/**
 * 
 */
public class AxialPosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
		return q;
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
		return r;
	}

	/**
	 * 
	 */
	public void equals() {
	}
}
