// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class AxialPosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
	}

	/**
	 * 
	 */
	public void equals() {
	}
}
