// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import board.AxialPosition.Direction;
import game.CatanSettings;
import structures.Road;
import structures.SettlementStructure;

/************************************************************/
/**
 * 
 */
public class Board {
	private Map<AxialPosition, Tile> tiles; // 19 Tiles
	private Map<NodePosition, Node> nodes; // 54 Nodes
	private Map<EdgePosition, Edge> edges; // 72 Edges

	private AxialPosition centre;
	private int size;
	
	/**
	 * 
	 */
	public Board() {
		tiles = new HashMap<>();
		nodes = new HashMap<>();
		edges = new HashMap<>();

		centre = new AxialPosition(0, 0);
		size = CatanSettings.BOARD_RADIUS;

		addTiles();
	}

	private void addTiles() {
		int tokenIndex = 0, tileIndex = 0;
		addTile(centre,
				CatanSettings.TOKEN_LAYOUT[tokenIndex], CatanSettings.STANDARD_BOARD_LAYOUT[tileIndex]);
		for (int ring = 1; ring <= size; ring++) {
			AxialPosition currentTilePosition = centre.add(Direction.DOWNLEFT.getVector().scale(ring));
			for (int i = 0; i < 6; i++) {
				for (int j = 0; j < ring; j++) {
					if (CatanSettings.STANDARD_BOARD_LAYOUT[tileIndex] != TileType.DESERT) {
						tokenIndex++;
					}
					
					tileIndex++;

					addTile(currentTilePosition,
							CatanSettings.TOKEN_LAYOUT[tokenIndex], CatanSettings.STANDARD_BOARD_LAYOUT[tileIndex]);
					// Enum is laid out such that indexing Direction.values()[i] will be correct
					currentTilePosition = currentTilePosition.neighbour(Direction.values()[i]);
				}
			}
		}
	}

	private void addTile(AxialPosition position, int token, TileType type) {
		if (type == TileType.DESERT) {
			token = 0;
		}

		Tile tile = new Tile(position, token, type);
		assignNodesToTile(tile);
		assignEdgesToTile(tile);

		for (EdgePosition edgePosition : tile.borders()) {
			Edge edge = tile.getEdge(edgePosition);
			Node startNode = nodes.get(edge.endpoints().get(0));
			Node endNode = nodes.get(edge.endpoints().get(1));
			edge.setNodes(startNode, endNode);

			if (!startNode.getEdges().contains(edge)) {
				startNode.addEdge(edge);
			}

			if (!endNode.getEdges().contains(edge)) {
				endNode.addEdge(edge);
			}
		}
		
		tiles.put(position, tile);
	}

	private void assignNodesToTile(Tile tile) {
		List<NodePosition> tileNodePositions = tile.corners();

		for (NodePosition nodePosition : tileNodePositions) {
			if (!nodes.containsKey(nodePosition)) {
				Node nodeToBeAdded = new Node(nodePosition);
				tile.addNode(nodeToBeAdded);
				nodes.put(nodePosition, nodeToBeAdded);
			} else {
				tile.addNode(nodes.get(nodePosition));
			}
		}
	}

	private void assignEdgesToTile(Tile tile) {
		List<EdgePosition> tileEdgePositions = tile.borders();

		for (EdgePosition edgePosition : tileEdgePositions) {
			if (!edges.containsKey(edgePosition)) {
				Edge edgeToBeAdded = new Edge(edgePosition);
				tile.addEdge(edgeToBeAdded);
				edges.put(edgePosition, edgeToBeAdded);
			} else {
				tile.addEdge(edges.get(edgePosition));
			}
		}
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Tile getTile(AxialPosition position) {
		return tiles.get(position);
	}

	
	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param structure 
	*/
	public void placeStructure(SettlementStructure structure) {
	}

	public void notifyTilesOfRoll(int roll) {
		for (Tile tile : tiles.values()) {
			tile.generateResource(roll);
		}
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder("Board: ");
		sb.append("(" + tiles.get(centre).getTileType() + ", " +
				tiles.get(centre).getPosition() + ", " + tiles.get(centre).getToken() + ")\n");
		for (int ring = 1; ring <= size; ring++) {
			AxialPosition currentTilePosition = centre.add(Direction.DOWNLEFT.getVector().scale(ring));
			for (int i = 0; i < 6; i++) {
				for (int j = 0; j < ring; j++) {
					Tile tile = tiles.get(currentTilePosition);
					sb.append("(" + tile + ", " + tile.getPosition() + ", " + tile.getToken() + ")\n");
					currentTilePosition = currentTilePosition.neighbour(Direction.values()[i]);
				}
			}
		}

		return sb.toString();
	}
}
