// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public void Board() {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Tile getTile(int index) {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void placeStructure(SettlementStructure structure) {
	}
}
