// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.List;

import structures.Road;
import structures.SettlementStructure;

/************************************************************/
/**
 * 
 */
public class Board {
	private List<Tile> tiles; // 19 Tiles
	private List<Node> nodes; // 54 Nodes
	private List<Edge> edges; // 72 Edges
	
	/**
	 * 
	 */
	public Board() {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Tile getTile(int index) {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void placeStructure(SettlementStructure structure) {
	}
}
