// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

/************************************************************/
/**
 * 
 */
public class EdgePosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;
	private RelativeEdgeLocation location;

	public EdgePosition(int q, int r, RelativeEdgeLocation direction) {

	}

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
	}

	/**
	 * 
	 * @return 
	 */
	public RelativeEdgeLocation getRelativeLocation() {
	}
}
