// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.List;

import structures.Road;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Road road;
	private EdgePosition position;
	private List<Node> connectedNodes;

	/**
	 * 
	 */
	public Edge() {
	}

	/**
	 * 
	 * @param startNode 
	 * @return 
	 */
	public Node getEnd(Node startNode) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
		return road;
	}
}
