// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Road structure;

	/**
	 * 
	 */
	public void Edge() {
	}

	/**
	 * 
	 * @param startNode 
	 * @return 
	 */
	public Node getEnd(Node startNode) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
	}
}
