// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class NodePosition {
	/**
	 * 
	 */
	public int q;
	/**
	 * 
	 */
	public int r;

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
	}

	/**
	 * 
	 * @return 
	 */
	public RelativeNodeLocation getRelativeLocation() {
	}

	/**
	 * 
	 */
	public void equals() {
	}
}
