// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.ArrayList;
import java.util.List;

import game.Player;
import game.Resource;
import structures.SettlementStructure;

/************************************************************/
/**
 * 
 */
public class Node {
	private List<Edge> edges;
	private NodePosition position;
	private SettlementStructure structure;
	/**
	 * 
	 */
	public Node(NodePosition position) {
		this.position = position;
		structure = null;

		edges = new ArrayList<>();
	}

	public Node(int q, int r, RelativeNodeLocation location, List<Edge> edges) {
		this.position = new NodePosition(q, r, location);
		structure = null;

		this.edges = edges;
	}

	public void notifyStructureOfResource(Resource resource) {
		structure.giveResourceToPlayer(resource);
	}

	public boolean hasStructure() {
		return structure != null;
	}

	public boolean canPlaceStructure(Player player) {
		boolean connectedRoad = false;
		for (Edge edge : edges) {
			if (edge.hasRoad() && edge.getRoad().getOwner().equals(player)) {
				connectedRoad = true;
			}
		}

		if (!connectedRoad) {
			return false;
		}

		// Distance rule
		return true;
	}

	public void placeStructure(SettlementStructure structure) {
		if (canPlaceStructure(structure.getOwner())) {
			this.structure = structure;
		} else {
			throw new IllegalStateException("Cannot place structure at " + position);
		}
	}

	public void addEdge(Edge edge) {
		if (edges.size() >= 3) {
			throw new IllegalStateException("Node cannot have more than 3 edges");
		}

		edges.add(edge);
	}

	public List<Edge> getEdges() {
		return new ArrayList<>(edges);
	}

	public NodePosition getPosition() {
		return position;
	}

	/**
	 * 
	 * @return 
	 */
	public SettlementStructure getStructure() {
		return structure;
	}

	/**
	 * 
	 *
	 */
	public String toString() {
		if (structure != null) {
			return structure.toString();
		} else {
			return "Empty Node";
		}
	}
}
