// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.List;

import structures.SettlementStructure;

/************************************************************/
/**
 * 
 */
public class Node {
	private List<Edge> edges;
	private NodePosition position;
	private SettlementStructure structure;
	/**
	 * 
	 */
	public Node() {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void setStructure(SettlementStructure structure) {
	}

	/**
	 * 
	 * @return 
	 */
	public SettlementStructure getStructure() {
	}

	/**
	 * 
	 * @param string 
	 */
	public void toString(String string) {
	}
}
