// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

/************************************************************/
/**
 * 
 */
public class NodePosition {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;
	private RelativeNodeLocation location;

	/**
	 * 
	 * @return 
	 */
	public int getQ() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getR() {
	}

	/**
	 * 
	 * @return 
	 */
	public RelativeNodeLocation getRelativeLocation() {
	}

	/**
	 * 
	 */
	public void equals() {
	}
}
