// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public void Node() {
	}

	/**
	 * 
	 * @param endNode 
	 * @return 
	 */
	public Edge getEdge(Node endNode) {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void setStructure(SettlementStructure structure) {
	}

	/**
	 * 
	 * @return 
	 */
	public SettlementStructure getStructure() {
	}

	/**
	 * 
	 * @param string 
	 */
	public void toString(String string) {
	}
}
