// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private TileType tileType;
	/**
	 * 
	 */
	private boolean blockedByRobber;
	/**
	 * 
	 */
	private int numberTokenValue;
	private List<Node> intersections;
	private AxialPosition position;

	/**
	 * 
	 * @param token 
	 * @param type 
	 * @param nodes 
	 */
	public Tile(int token, TileType type) {
	}

	/**
	 * 
	 * @return 
	 */
	public void getTileType() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken() {
	}

	/**
	 * 
	 * @param robber 
	 */
	public void setBlockedByRobber(boolean robber) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isBlockedByRobber() {
	}

	/**
	 * 
	 * @return 
	 */
	public List<Node> getNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
