// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment_1;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private TileType tileType;
	/**
	 * 
	 */
	private boolean blockedByRobber;
	/**
	 * 
	 */
	private int numberTokenValue;

	/**
	 * 
	 * @param token 
	 * @param type 
	 * @param nodes 
	 */
	public void Tile(int token, TileType type, Node[] nodes) {
	}

	/**
	 * 
	 * @return 
	 */
	public void getTileType() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken() {
	}

	/**
	 * 
	 * @param robber 
	 */
	public void setBlockedByRobber(boolean robber) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean getBlockedByRobber() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
