// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package board;

import game.Resource;

/************************************************************/
/**
 * 
 */
public enum TileType {
	/**
	 * 
	 */
	FOREST(Resource.WOOD),
	/**
	 * 
	 */
	PASTURE(Resource.SHEEP),
	/**
	 * 
	 */
	FIELD(Resource.WHEAT),
	/**
	 * 
	 */
	HILLS(Resource.BRICK),
	/**
	 * 
	 */
	MOUNTAIN(Resource.ORE),
	/**
	 * 
	 */
	DESERT(null);

	private final Resource producedResource;

	private TileType(Resource resource) {
		producedResource = resource;
	}

	public Resource getProducedResource() {
		return producedResource;
	}
}
